from typing import Any, Dict, List, NamedTuple, Optional

__version__: str

class NetmatError(Exception): ...

class Incidence(NamedTuple):
    A: Any  # scipy.sparse.csr_matrix
    b: Any  # numpy.ndarray
    p_shift: Any  # numpy.ndarray
    branch_of_col: Any  # numpy.ndarray

class Case:
    name: str
    base_mva: float
    n: int
    n_branches: int
    n_gens: int
    is_radial: bool
    n_connected_components: int
    buses: List[Dict[str, Any]]
    branches: List[Dict[str, Any]]
    gens: List[Dict[str, Any]]
    def reference_bus_index(self) -> int: ...
    def connectivity_report(self) -> Dict[str, Any]: ...
    def bprime(self, scheme: str = ...) -> Any: ...
    def bdoubleprime(self, include_taps: bool = ...) -> Any: ...
    def lacpf(self, include_taps: bool = ..., include_shifts: bool = ...) -> Any: ...
    def adjacency(self) -> Any: ...
    def ybus_parts(
        self, include_taps: bool = ..., include_shifts: bool = ...
    ) -> tuple[Any, Any]: ...
    def ybus(self, include_taps: bool = ..., include_shifts: bool = ...) -> Any: ...
    def ptdf(self, convention: str = ...) -> Any: ...
    def lodf(self, convention: str = ...) -> Any: ...
    def weighted_laplacian(self, convention: str = ...) -> Any: ...
    def incidence(self, convention: str = ...) -> Incidence: ...
    def to_networkx(self) -> Any: ...
    def write_dcopf_bundle(
        self, out_dir: str, convention: str = ..., units: str = ...
    ) -> Dict[str, Any]: ...

def parse_matpower(path: Any) -> Case: ...
def parse_matpower_string(content: str, name: Optional[str] = ...) -> Case: ...
