//! PMD ENGINEERING JSON reader/writer against reference JSON generated by
//! PowerModelsDistribution itself (tests/data/dist/pmd, provenance in the
//! fixture README).

use std::collections::BTreeSet;
use std::path::PathBuf;
use std::sync::Arc;

use powerio_dist::dss::parse_dss_file;
use powerio_dist::{DistNetwork, parse_pmd_file, parse_pmd_str, write_bmopf_json, write_pmd_json};

fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tests/data/dist")
        .join(rel)
}

#[test]
#[allow(clippy::float_cmp)]
fn parse_the_reference_engineering_json() {
    let net = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();
    assert_eq!(net.name.as_deref(), Some("ieee13nodeckt"));
    assert_eq!(net.buses.len(), 16);
    assert_eq!(net.lines.len(), 11);
    assert_eq!(net.switches.len(), 1);
    assert_eq!(net.loads.len(), 15);
    assert_eq!(net.shunts.len(), 2);
    assert_eq!(net.transformers.len(), 3); // sub, xfm1, reg1 (banked)
    assert_eq!(net.sources.len(), 1);

    let b611 = net.bus("611").unwrap();
    assert_eq!(b611.terminals, vec!["3", "4"]);
    assert_eq!(b611.grounded, vec!["4"]);

    // kW scale restores to watts; degrees to radians.
    let l611 = net.loads.iter().find(|l| l.name == "611").unwrap();
    assert!((l611.p_nom[0] - 170_000.0).abs() < 1e-9);
    let vs = &net.sources[0];
    assert!((vs.v_magnitude[0] - 66_401.920_484_902_64).abs() < 1e-6);
    assert!((vs.v_angle[0] - 30f64.to_radians()).abs() < 1e-9);
    assert_eq!(vs.v_magnitude.len(), 4);
    assert_eq!(vs.v_magnitude[3], 0.0);
}

/// The PMD oracle agreement: PMD's own parse of IEEE13 and ours agree on
/// the network content.
#[test]
fn dss_parse_agrees_with_the_pmd_parse() {
    let ours = parse_dss_file(fixture("opendss/ieee13/IEEE13Nodeckt.dss")).unwrap();
    let pmd = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();

    let bus_set = |n: &DistNetwork| -> BTreeSet<String> {
        n.buses.iter().map(|b| b.id.to_lowercase()).collect()
    };
    assert_eq!(bus_set(&ours), bus_set(&pmd));

    // Terminals and grounding agree bus by bus.
    for b in &ours.buses {
        let other = pmd.bus(&b.id).unwrap();
        assert_eq!(b.terminals, other.terminals, "bus {}", b.id);
        assert_eq!(b.grounded, other.grounded, "bus {}", b.id);
    }

    // Linecode series impedance agrees on mtx601 to the mile rounding:
    // PMD converts with 1609.3 m per mile, the engine with the exact
    // 1609.344, a 2.7e-5 relative difference carried into every per meter
    // value. powerio-dist uses the engine's factor.
    let a = ours.linecode("mtx601").unwrap();
    let b = pmd.linecode("mtx601").unwrap();
    let close = |x: f64, y: f64| (x - y).abs() <= 5e-5 * x.abs().max(y.abs()).max(1e-30);
    for i in 0..3 {
        for j in 0..3 {
            assert!(close(a.r_series[i][j], b.r_series[i][j]));
            assert!(close(a.x_series[i][j], b.x_series[i][j]));
            assert!(close(a.b_from[i][j], b.b_from[i][j]));
        }
    }
    assert_eq!(a.i_max, b.i_max);

    // Loads agree in power, configuration, and connection.
    for l in &ours.loads {
        let other = pmd
            .loads
            .iter()
            .find(|o| o.name.eq_ignore_ascii_case(&l.name))
            .unwrap();
        for (p, q) in l.p_nom.iter().zip(&other.p_nom) {
            assert!((p - q).abs() < 1e-9, "load {}", l.name);
        }
        assert_eq!(l.terminal_map, other.terminal_map, "load {}", l.name);
    }

    // The switch state and ampacity agree.
    assert_eq!(ours.switches[0].open, pmd.switches[0].open);
    assert_eq!(ours.switches[0].i_max, pmd.switches[0].i_max);

    // Source magnitude and angles agree.
    let (vs_a, vs_b) = (&ours.sources[0], &pmd.sources[0]);
    for (m, o) in vs_a.v_magnitude.iter().zip(&vs_b.v_magnitude) {
        assert!((m - o).abs() < 1e-6);
    }
    for (m, o) in vs_a.v_angle.iter().zip(&vs_b.v_angle) {
        assert!((m - o).abs() < 1e-9);
    }
}

#[test]
fn four_wire_reference_agrees() {
    let ours = parse_dss_file(fixture("micro/fourwire_linecode.dss")).unwrap();
    let pmd = parse_pmd_file(fixture("pmd/fourwire_linecode.json")).unwrap();
    let a = ours.linecode("lc4").unwrap();
    let b = pmd.linecode("lc4").unwrap();
    assert_eq!(a.n_conductors, b.n_conductors);
    for i in 0..4 {
        for j in 0..4 {
            assert!((a.r_series[i][j] - b.r_series[i][j]).abs() < 1e-15);
        }
    }
    let la = ours.loads.iter().find(|l| l.name == "la").unwrap();
    let lb = pmd.loads.iter().find(|l| l.name == "la").unwrap();
    assert_eq!(la.terminal_map, lb.terminal_map);
    assert!((la.p_nom[0] - lb.p_nom[0]).abs() < 1e-9);
}

#[test]
fn canonical_output_is_idempotent() {
    let net = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();
    let once = write_pmd_json(&net);
    let again = parse_pmd_str(&once.text).unwrap();
    let twice = write_pmd_json(&again);
    assert_eq!(once.text, twice.text);
}

/// Model equality after a P round trip, minus the retained source.
#[test]
fn pmd_round_trips_to_model_equality() {
    let net = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();
    let out = write_pmd_json(&net);
    let again = parse_pmd_str(&out.text).unwrap();
    let strip = |n: &DistNetwork| {
        let mut n = n.clone();
        n.source = Some(Arc::new(String::new()));
        n.extras.clear(); // pmd_settings/pmd_files bookkeeping differs in formatting only
        n.warnings.clear();
        n
    };
    let (a, b) = (strip(&net), strip(&again));
    assert_eq!(a.buses, b.buses);
    assert_eq!(a.lines, b.lines);
    assert_eq!(a.switches, b.switches);
    assert_eq!(a.loads, b.loads);
    assert_eq!(a.shunts, b.shunts);
    assert_eq!(a.sources, b.sources);
    assert_eq!(a.linecodes, b.linecodes);
    assert_eq!(a.transformers, b.transformers);
}

#[test]
fn dss_to_pmd_reproduces_the_reference_essentials() {
    let net = parse_dss_file(fixture("opendss/ieee13/IEEE13Nodeckt.dss")).unwrap();
    let out = write_pmd_json(&net);
    let emitted: serde_json::Value = serde_json::from_str(&out.text).unwrap();
    let reference: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixture("pmd/ieee13.json")).unwrap())
            .unwrap();

    assert_eq!(emitted["data_model"], reference["data_model"]);
    // Bus terminals, grounding, and coordinates match the reference.
    for (id, bus) in reference["bus"].as_object().unwrap() {
        let ours = &emitted["bus"][id];
        assert_eq!(ours["terminals"], bus["terminals"], "bus {id}");
        assert_eq!(ours["grounded"], bus["grounded"], "bus {id}");
        assert_eq!(ours["lat"], bus["lat"], "bus {id}");
        assert_eq!(ours["status"], bus["status"], "bus {id}");
    }
    // Loads match in power, model enum, and nominal voltage.
    for (id, load) in reference["load"].as_object().unwrap() {
        let ours = &emitted["load"][id];
        assert_eq!(ours["pd_nom"], load["pd_nom"], "load {id}");
        assert_eq!(ours["qd_nom"], load["qd_nom"], "load {id}");
        assert_eq!(ours["model"], load["model"], "load {id}");
        assert_eq!(ours["vm_nom"], load["vm_nom"], "load {id}");
        assert_eq!(ours["configuration"], load["configuration"], "load {id}");
        assert_eq!(ours["connections"], load["connections"], "load {id}");
    }
    // The switch reproduces PMD's tiny series resistance convention.
    assert_eq!(
        emitted["switch"]["671692"]["rs"],
        reference["switch"]["671692"]["rs"]
    );
    assert_eq!(
        emitted["switch"]["671692"]["state"],
        reference["switch"]["671692"]["state"]
    );
    // The voltage source Thevenin matrices match the engine's computation.
    let ours_rs = emitted["voltage_source"]["source"]["rs"]
        .as_array()
        .unwrap();
    let ref_rs = reference["voltage_source"]["source"]["rs"]
        .as_array()
        .unwrap();
    for (a, b) in ours_rs.iter().zip(ref_rs) {
        for (x, y) in a.as_array().unwrap().iter().zip(b.as_array().unwrap()) {
            assert!((x.as_f64().unwrap() - y.as_f64().unwrap()).abs() < 1e-9);
        }
    }
    // Transformer per unit impedances and taps match (sub: delta primary).
    for id in ["sub", "xfm1"] {
        let ours = &emitted["transformer"][id];
        let want = &reference["transformer"][id];
        assert_eq!(ours["rw"], want["rw"], "{id}");
        assert_eq!(ours["xsc"], want["xsc"], "{id}");
        assert_eq!(ours["vm_nom"], want["vm_nom"], "{id}");
        assert_eq!(ours["sm_nom"], want["sm_nom"], "{id}");
        assert_eq!(ours["polarity"], want["polarity"], "{id}");
        assert_eq!(ours["connections"], want["connections"], "{id}");
        assert_eq!(ours["tm_step"], want["tm_step"], "{id}");
    }
}

fn rewrite(text: &str) -> serde_json::Value {
    let net = parse_pmd_str(text).unwrap();
    serde_json::from_str(&write_pmd_json(&net).text).unwrap()
}

/// A non ENABLED status survives the round trip on every component class
/// instead of silently re-enabling.
#[test]
fn disabled_status_round_trips() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "bus": {
            "b1": {"terminals": [1, 2, 3, 4], "grounded": [4], "rg": [0.0], "xg": [0.0], "status": "DISABLED"},
            "b2": {"terminals": [1, 2, 3, 4], "grounded": [4], "rg": [0.0], "xg": [0.0], "status": "ENABLED"}
        },
        "linecode": {"lc": {"rs": [[0.1]], "xs": [[0.1]], "g_fr": [[0.0]], "g_to": [[0.0]], "b_fr": [[0.0]], "b_to": [[0.0]]}},
        "line": {"ln": {"f_bus": "b1", "t_bus": "b2", "f_connections": [1], "t_connections": [1],
            "linecode": "lc", "length": 10.0, "status": "DISABLED"}},
        "switch": {"sw": {"f_bus": "b1", "t_bus": "b2", "f_connections": [1], "t_connections": [1],
            "state": "CLOSED", "status": "DISABLED"}},
        "load": {"ld": {"bus": "b1", "connections": [1, 4], "configuration": "WYE",
            "pd_nom": [5.0], "qd_nom": [1.0], "status": "DISABLED"}},
        "generator": {"gn": {"bus": "b1", "connections": [1, 2, 3, 4], "configuration": "WYE",
            "pg": [10.0, 10.0, 10.0], "qg": [0.0, 0.0, 0.0], "status": "DISABLED"}},
        "shunt": {"sh": {"bus": "b1", "connections": [1, 4], "gs": [[0.0]], "bs": [[1.0]], "status": "DISABLED"}},
        "voltage_source": {"src": {"bus": "b1", "connections": [1, 2, 3, 4],
            "vm": [7.2, 7.2, 7.2, 0.0], "va": [0.0, -120.0, 120.0, 0.0], "status": "DISABLED"}},
        "transformer": {"tr": {"bus": ["b1", "b2"], "connections": [[1, 2, 3, 4], [1, 2, 3, 4]],
            "configuration": ["WYE", "WYE"], "polarity": [1, 1], "rw": [0.01, 0.01], "xsc": [0.05],
            "sm_nom": [500.0, 500.0], "vm_nom": [12.47, 4.16],
            "tm_set": [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]], "status": "DISABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    assert!(
        net.warnings
            .iter()
            .any(|w| w.contains("status DISABLED kept in extras"))
    );
    let out = rewrite(text);
    for (class, name) in [
        ("bus", "b1"),
        ("line", "ln"),
        ("switch", "sw"),
        ("load", "ld"),
        ("generator", "gn"),
        ("shunt", "sh"),
        ("voltage_source", "src"),
        ("transformer", "tr"),
    ] {
        assert_eq!(out[class][name]["status"], "DISABLED", "{class} {name}");
    }
    // Untouched elements stay enabled.
    assert_eq!(out["bus"]["b2"]["status"], "ENABLED");
}

/// A euro (lead) Dy transformer: polarity [1, 1] with unrolled secondary
/// connections must come back verbatim, not flipped to the ANSI lag roll.
#[test]
fn euro_lead_transformer_round_trips() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "transformer": {"tr": {"bus": ["b1", "b2"],
            "connections": [[1, 2, 3], [1, 2, 3, 4]],
            "configuration": ["DELTA", "WYE"], "polarity": [1, 1],
            "rw": [0.01, 0.01], "xsc": [0.05],
            "sm_nom": [500.0, 500.0], "vm_nom": [12.47, 4.16],
            "tm_set": [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]], "status": "ENABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    // No undo: the file is not in the lag convention, so the model holds
    // the connections as written and the raw polarity rides in extras.
    let t = &net.transformers[0];
    assert_eq!(t.windings[1].terminal_map, vec!["1", "2", "3", "4"]);
    assert!(t.extras.contains_key("pmd_polarity"));

    let out = rewrite(text);
    assert_eq!(
        out["transformer"]["tr"]["polarity"],
        serde_json::json!([1, 1])
    );
    assert_eq!(
        out["transformer"]["tr"]["connections"],
        serde_json::json!([[1, 2, 3], [1, 2, 3, 4]])
    );
}

/// The ANSI lag Dy transformer (the dss2eng output: polarity -1 with the
/// barrel rolled secondary) reproduces its input through the model.
#[test]
fn ansi_lag_transformer_round_trips() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "transformer": {"tr": {"bus": ["b1", "b2"],
            "connections": [[1, 2, 3], [2, 3, 1, 4]],
            "configuration": ["DELTA", "WYE"], "polarity": [1, -1],
            "rw": [0.01, 0.01], "xsc": [0.05],
            "sm_nom": [500.0, 500.0], "vm_nom": [12.47, 4.16],
            "tm_set": [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]], "status": "ENABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    // The roll is undone in the model (the dss source order) and nothing
    // needs a stash: the writer's lag convention reproduces the file.
    let t = &net.transformers[0];
    assert_eq!(t.windings[1].terminal_map, vec!["1", "2", "3", "4"]);
    assert!(!t.extras.contains_key("pmd_polarity"));

    let out = rewrite(text);
    assert_eq!(
        out["transformer"]["tr"]["polarity"],
        serde_json::json!([1, -1])
    );
    assert_eq!(
        out["transformer"]["tr"]["connections"],
        serde_json::json!([[1, 2, 3], [2, 3, 1, 4]])
    );
}

/// A line with inline impedance (the dss2eng output for rmatrix defined
/// lines) keeps its matrices: the reader materializes a linecode and the
/// writer re-inlines it without a linecode key.
#[test]
fn inline_line_impedance_round_trips() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "bus": {
            "b1": {"terminals": [1, 2], "grounded": [], "rg": [], "xg": [], "status": "ENABLED"},
            "b2": {"terminals": [1, 2], "grounded": [], "rg": [], "xg": [], "status": "ENABLED"}
        },
        "line": {"ln1": {"f_bus": "b1", "t_bus": "b2",
            "f_connections": [1, 2], "t_connections": [1, 2], "length": 304.8,
            "rs": [[0.1, 0.02], [0.02, 0.1]], "xs": [[0.2, 0.05], [0.05, 0.2]],
            "g_fr": [[0.0, 0.0], [0.0, 0.0]], "g_to": [[0.0, 0.0], [0.0, 0.0]],
            "b_fr": [[1.7, -0.4], [-0.4, 1.7]], "b_to": [[1.7, -0.4], [-0.4, 1.7]],
            "cm_ub": [400.0, 400.0], "status": "ENABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    let l = &net.lines[0];
    assert_eq!(l.linecode, "ln1_z");
    assert_eq!(l.extras.get("pmd_inline"), Some(&serde_json::json!(true)));
    let c = net.linecode("ln1_z").unwrap();
    assert!((c.r_series[0][1] - 0.02).abs() < 1e-15);
    assert_eq!(c.i_max.as_deref(), Some(&[400.0, 400.0][..]));
    assert!(net.warnings.iter().any(|w| w.contains("materialized")));

    let input: serde_json::Value = serde_json::from_str(text).unwrap();
    let out = rewrite(text);
    let line = &out["line"]["ln1"];
    for key in ["rs", "xs", "g_fr", "g_to", "b_fr", "b_to", "cm_ub"] {
        assert_eq!(line[key], input["line"]["ln1"][key], "{key}");
    }
    assert!(line.get("linecode").is_none());
    // The materialized linecode does not leak into the linecode section.
    assert!(out.get("linecode").is_none());
}

/// Per phase taps and custom bounds survive: the raw tm_* arrays ride in
/// extras and the writer prefers them over the engine defaults.
#[test]
#[allow(clippy::float_cmp)]
fn per_phase_taps_round_trip() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "transformer": {"reg": {"bus": ["b1", "b2"],
            "connections": [[1, 2, 3, 4], [1, 2, 3, 4]],
            "configuration": ["WYE", "WYE"], "polarity": [1, 1],
            "rw": [0.005, 0.005], "xsc": [0.01],
            "sm_nom": [1666.0, 1666.0], "vm_nom": [2.4, 2.4],
            "tm_set": [[1.0, 1.0, 1.0], [1.05625, 1.04375, 1.05]],
            "tm_lb": [[0.85, 0.85, 0.85], [0.85, 0.85, 0.85]],
            "tm_ub": [[1.15, 1.15, 1.15], [1.15, 1.15, 1.15]],
            "tm_fix": [[true, true, true], [false, false, false]],
            "tm_step": [[0.0625, 0.0625, 0.0625], [0.0625, 0.0625, 0.0625]],
            "status": "ENABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    assert_eq!(net.transformers[0].windings[1].tap, 1.05625);
    assert!(net.warnings.iter().any(|w| w.contains("per phase taps")));

    let input: serde_json::Value = serde_json::from_str(text).unwrap();
    let out = rewrite(text);
    for key in ["tm_set", "tm_lb", "tm_ub", "tm_fix", "tm_step"] {
        assert_eq!(
            out["transformer"]["reg"][key], input["transformer"]["reg"][key],
            "{key}"
        );
    }
}

/// The settings object and files array come back verbatim from the
/// reader's stash instead of being resynthesized.
#[test]
fn settings_and_files_round_trip() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "files": ["a.dss", "b.dss"],
        "settings": {"base_frequency": 50.0, "power_scale_factor": 1000.0,
            "voltage_scale_factor": 1000.0, "sbase_default": 500.0,
            "vbases_default": {"slack": 7.2}},
        "bus": {"slack": {"terminals": [1], "grounded": [], "rg": [], "xg": [], "status": "ENABLED"}}
    }"#;
    let input: serde_json::Value = serde_json::from_str(text).unwrap();
    let out = rewrite(text);
    assert_eq!(out["settings"], input["settings"]);
    assert_eq!(out["files"], input["files"]);
}

/// dss sourced settings synthesize with the dss2eng conventions: the vbase
/// is basekv over sqrt(phases) without the pu factor, sbase the basemva
/// default — matching the reference export bit for bit.
#[test]
fn dss_settings_match_the_reference() {
    let net = parse_dss_file(fixture("opendss/ieee13/IEEE13Nodeckt.dss")).unwrap();
    let out: serde_json::Value = serde_json::from_str(&write_pmd_json(&net).text).unwrap();
    let reference: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixture("pmd/ieee13.json")).unwrap())
            .unwrap();
    // IEEE13 sets pu=1.0001; the vbase must not fold it in.
    assert_eq!(
        out["settings"]["vbases_default"],
        reference["settings"]["vbases_default"]
    );
    assert_eq!(
        out["settings"]["sbase_default"],
        reference["settings"]["sbase_default"]
    );
}

/// Nonzero bus grounding impedance comes back from the extras stash
/// instead of zero vectors.
#[test]
fn grounding_impedance_round_trips() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "bus": {"b1": {"terminals": [1, 2, 3, 4], "grounded": [4],
            "rg": [5.0], "xg": [12.0], "status": "ENABLED"}}
    }"#;
    let out = rewrite(text);
    assert_eq!(out["bus"]["b1"]["rg"], serde_json::json!([5.0]));
    assert_eq!(out["bus"]["b1"]["xg"], serde_json::json!([12.0]));
}

/// A switch's real series matrices win over the engine's 1e-7 dummy, and
/// a linecode's sm_ub survives through s_max.
#[test]
fn switch_impedance_and_sm_ub_round_trip() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "linecode": {"lc": {"rs": [[0.1]], "xs": [[0.1]],
            "g_fr": [[0.0]], "g_to": [[0.0]], "b_fr": [[0.0]], "b_to": [[0.0]],
            "cm_ub": [400.0], "sm_ub": [600.0]}},
        "switch": {"sw": {"f_bus": "b1", "t_bus": "b2",
            "f_connections": [1, 2], "t_connections": [1, 2], "state": "CLOSED",
            "rs": [[0.03, 0.01], [0.01, 0.03]], "xs": [[0.04, 0.02], [0.02, 0.04]],
            "status": "ENABLED"}}
    }"#;
    let input: serde_json::Value = serde_json::from_str(text).unwrap();
    let out = rewrite(text);
    assert_eq!(out["switch"]["sw"]["rs"], input["switch"]["sw"]["rs"]);
    assert_eq!(out["switch"]["sw"]["xs"], input["switch"]["sw"]["xs"]);
    assert_eq!(
        out["linecode"]["lc"]["sm_ub"],
        input["linecode"]["lc"]["sm_ub"]
    );
}

/// An inline impedance line whose `{name}_z` collides with a code in the
/// document's own linecode section. The fixed section order processes
/// "linecode" before "line" (serde_json's sorted maps would visit "line"
/// first and miss the collision), so the materialized inline code takes
/// the `_z2` suffix instead of duplicating the name.
#[test]
fn inline_linecode_collision_with_document_linecode() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "linecode": {"foo_z": {"rs": [[0.5]], "xs": [[0.9]]}},
        "line": {
            "bar": {"f_bus": "b2", "t_bus": "b3", "f_connections": [1], "t_connections": [1],
                "linecode": "foo_z", "length": 1.0, "status": "ENABLED"},
            "foo": {"f_bus": "b1", "t_bus": "b2", "f_connections": [1], "t_connections": [1],
                "length": 1.0, "rs": [[0.111]], "xs": [[0.222]], "status": "ENABLED"}
        }
    }"#;
    let net = parse_pmd_str(text).unwrap();

    let names: BTreeSet<&str> = net.linecodes.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(net.linecodes.len(), 2);
    assert!(names.contains("foo_z") && names.contains("foo_z2"));

    let foo = net.lines.iter().find(|l| l.name == "foo").unwrap();
    assert_eq!(foo.linecode, "foo_z2");
    assert!((net.linecode("foo_z2").unwrap().r_series[0][0] - 0.111).abs() < 1e-15);
    let bar = net.lines.iter().find(|l| l.name == "bar").unwrap();
    assert_eq!(bar.linecode, "foo_z");
    assert!((net.linecode("foo_z").unwrap().r_series[0][0] - 0.5).abs() < 1e-15);

    // The BMOPF projection keys linecodes by name; line foo must carry its
    // own 0.111, not the document code's 0.5.
    let out = write_bmopf_json(&net);
    let doc: serde_json::Value = serde_json::from_str(&out.text).unwrap();
    let code = doc["line"]["foo"]["linecode"].as_str().unwrap();
    assert_eq!(code, "foo_z2");
    assert_eq!(
        doc["linecode"][code]["R_series_1_1"],
        serde_json::json!(0.111)
    );
}

/// A linecode carrying only a 10x10 xs sizes from the widest matrix, not
/// rs alone: n_conductors is 10 and rs reads as zero padding. Present
/// matrices that disagree in size pad with a warning naming the code.
#[test]
#[allow(clippy::float_cmp)]
fn linecode_sized_from_widest_matrix() {
    let xs: Vec<Vec<f64>> = (0..10)
        .map(|i| (0..10).map(|j| if i == j { 0.9 } else { 0.1 }).collect())
        .collect();
    let text = serde_json::json!({
        "data_model": "ENGINEERING",
        "linecode": {
            "wide": {"xs": xs},
            "ragged": {"rs": [[0.1]], "xs": [[0.2, 0.0], [0.0, 0.2]]}
        }
    })
    .to_string();
    let net = parse_pmd_str(&text).unwrap();

    let c = net.linecode("wide").unwrap();
    assert_eq!(c.n_conductors, 10);
    assert_eq!(c.r_series, vec![vec![0.0; 10]; 10]);
    assert_eq!(c.x_series[9][9], 0.9);

    let r = net.linecode("ragged").unwrap();
    assert_eq!(r.n_conductors, 2);
    assert_eq!(r.r_series, vec![vec![0.1, 0.0], vec![0.0, 0.0]]);
    assert!(
        net.warnings
            .iter()
            .any(|w| w.contains("linecode ragged: matrix sizes disagree"))
    );

    let out = write_bmopf_json(&net);
    assert!(
        out.warnings
            .iter()
            .all(|w| !w.contains("double digit matrix keys")),
        "obsolete double digit warning still emitted: {:?}",
        out.warnings
    );
}

#[test]
fn null_suffix_restoration() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "bus": {"a": {"terminals": [1], "grounded": [], "rg": [], "xg": [], "status": "ENABLED"}},
        "linecode": {"c": {"rs": [[1.0]], "xs": [[1.0]],
            "g_fr": [[0.0]], "g_to": [[0.0]], "b_fr": [[0.0]], "b_to": [[0.0]],
            "cm_ub": [null]}},
        "voltage_source": {"src": {"bus": "a", "connections": [1],
            "vm": [0.24], "va": [0.0], "status": "ENABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    // cm_ub null restores to +Inf under the `_ub` suffix; an infinite
    // ampacity bound means no bound, so i_max is None.
    assert!(net.linecodes[0].i_max.is_none());
}
