//! PMD ENGINEERING JSON reader/writer against reference JSON generated by
//! PowerModelsDistribution itself (tests/data/dist/pmd, provenance in the
//! fixture README).

use std::collections::BTreeSet;
use std::path::PathBuf;
use std::sync::Arc;

use powerio_dist::dss::parse_dss_file;
use powerio_dist::{DistNetwork, parse_pmd_file, parse_pmd_str, write_pmd_json};

fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../tests/data/dist")
        .join(rel)
}

#[test]
#[allow(clippy::float_cmp)]
fn parse_the_reference_engineering_json() {
    let net = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();
    assert_eq!(net.name.as_deref(), Some("ieee13nodeckt"));
    assert_eq!(net.buses.len(), 16);
    assert_eq!(net.lines.len(), 11);
    assert_eq!(net.switches.len(), 1);
    assert_eq!(net.loads.len(), 15);
    assert_eq!(net.shunts.len(), 2);
    assert_eq!(net.transformers.len(), 3); // sub, xfm1, reg1 (banked)
    assert_eq!(net.sources.len(), 1);

    let b611 = net.bus("611").unwrap();
    assert_eq!(b611.terminals, vec!["3", "4"]);
    assert_eq!(b611.grounded, vec!["4"]);

    // kW scale restores to watts; degrees to radians.
    let l611 = net.loads.iter().find(|l| l.name == "611").unwrap();
    assert!((l611.p_nom[0] - 170_000.0).abs() < 1e-9);
    let vs = &net.sources[0];
    assert!((vs.v_magnitude[0] - 66_401.920_484_902_64).abs() < 1e-6);
    assert!((vs.v_angle[0] - 30f64.to_radians()).abs() < 1e-9);
    assert_eq!(vs.v_magnitude.len(), 4);
    assert_eq!(vs.v_magnitude[3], 0.0);
}

/// The PMD oracle agreement: PMD's own parse of IEEE13 and ours agree on
/// the network content.
#[test]
fn dss_parse_agrees_with_the_pmd_parse() {
    let ours = parse_dss_file(fixture("opendss/ieee13/IEEE13Nodeckt.dss")).unwrap();
    let pmd = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();

    let bus_set = |n: &DistNetwork| -> BTreeSet<String> {
        n.buses.iter().map(|b| b.id.to_lowercase()).collect()
    };
    assert_eq!(bus_set(&ours), bus_set(&pmd));

    // Terminals and grounding agree bus by bus.
    for b in &ours.buses {
        let other = pmd.bus(&b.id).unwrap();
        assert_eq!(b.terminals, other.terminals, "bus {}", b.id);
        assert_eq!(b.grounded, other.grounded, "bus {}", b.id);
    }

    // Linecode series impedance agrees on mtx601 to the mile rounding:
    // PMD converts with 1609.3 m per mile, the engine with the exact
    // 1609.344, a 2.7e-5 relative difference carried into every per meter
    // value. powerio-dist uses the engine's factor.
    let a = ours.linecode("mtx601").unwrap();
    let b = pmd.linecode("mtx601").unwrap();
    let close = |x: f64, y: f64| (x - y).abs() <= 5e-5 * x.abs().max(y.abs()).max(1e-30);
    for i in 0..3 {
        for j in 0..3 {
            assert!(close(a.r_series[i][j], b.r_series[i][j]));
            assert!(close(a.x_series[i][j], b.x_series[i][j]));
            assert!(close(a.b_from[i][j], b.b_from[i][j]));
        }
    }
    assert_eq!(a.i_max, b.i_max);

    // Loads agree in power, configuration, and connection.
    for l in &ours.loads {
        let other = pmd
            .loads
            .iter()
            .find(|o| o.name.eq_ignore_ascii_case(&l.name))
            .unwrap();
        for (p, q) in l.p_nom.iter().zip(&other.p_nom) {
            assert!((p - q).abs() < 1e-9, "load {}", l.name);
        }
        assert_eq!(l.terminal_map, other.terminal_map, "load {}", l.name);
    }

    // The switch state and ampacity agree.
    assert_eq!(ours.switches[0].open, pmd.switches[0].open);
    assert_eq!(ours.switches[0].i_max, pmd.switches[0].i_max);

    // Source magnitude and angles agree.
    let (vs_a, vs_b) = (&ours.sources[0], &pmd.sources[0]);
    for (m, o) in vs_a.v_magnitude.iter().zip(&vs_b.v_magnitude) {
        assert!((m - o).abs() < 1e-6);
    }
    for (m, o) in vs_a.v_angle.iter().zip(&vs_b.v_angle) {
        assert!((m - o).abs() < 1e-9);
    }
}

#[test]
fn four_wire_reference_agrees() {
    let ours = parse_dss_file(fixture("micro/fourwire_linecode.dss")).unwrap();
    let pmd = parse_pmd_file(fixture("pmd/fourwire_linecode.json")).unwrap();
    let a = ours.linecode("lc4").unwrap();
    let b = pmd.linecode("lc4").unwrap();
    assert_eq!(a.n_conductors, b.n_conductors);
    for i in 0..4 {
        for j in 0..4 {
            assert!((a.r_series[i][j] - b.r_series[i][j]).abs() < 1e-15);
        }
    }
    let la = ours.loads.iter().find(|l| l.name == "la").unwrap();
    let lb = pmd.loads.iter().find(|l| l.name == "la").unwrap();
    assert_eq!(la.terminal_map, lb.terminal_map);
    assert!((la.p_nom[0] - lb.p_nom[0]).abs() < 1e-9);
}

#[test]
fn canonical_output_is_idempotent() {
    let net = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();
    let once = write_pmd_json(&net);
    let again = parse_pmd_str(&once.text).unwrap();
    let twice = write_pmd_json(&again);
    assert_eq!(once.text, twice.text);
}

/// Model equality after a P round trip, minus the retained source.
#[test]
fn pmd_round_trips_to_model_equality() {
    let net = parse_pmd_file(fixture("pmd/ieee13.json")).unwrap();
    let out = write_pmd_json(&net);
    let again = parse_pmd_str(&out.text).unwrap();
    let strip = |n: &DistNetwork| {
        let mut n = n.clone();
        n.source = Some(Arc::new(String::new()));
        n.extras.clear(); // pmd_settings/pmd_files bookkeeping differs in formatting only
        n.warnings.clear();
        n
    };
    let (a, b) = (strip(&net), strip(&again));
    assert_eq!(a.buses, b.buses);
    assert_eq!(a.lines, b.lines);
    assert_eq!(a.switches, b.switches);
    assert_eq!(a.loads, b.loads);
    assert_eq!(a.shunts, b.shunts);
    assert_eq!(a.sources, b.sources);
    assert_eq!(a.linecodes, b.linecodes);
    assert_eq!(a.transformers, b.transformers);
}

#[test]
fn dss_to_pmd_reproduces_the_reference_essentials() {
    let net = parse_dss_file(fixture("opendss/ieee13/IEEE13Nodeckt.dss")).unwrap();
    let out = write_pmd_json(&net);
    let emitted: serde_json::Value = serde_json::from_str(&out.text).unwrap();
    let reference: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixture("pmd/ieee13.json")).unwrap())
            .unwrap();

    assert_eq!(emitted["data_model"], reference["data_model"]);
    // Bus terminals, grounding, and coordinates match the reference.
    for (id, bus) in reference["bus"].as_object().unwrap() {
        let ours = &emitted["bus"][id];
        assert_eq!(ours["terminals"], bus["terminals"], "bus {id}");
        assert_eq!(ours["grounded"], bus["grounded"], "bus {id}");
        assert_eq!(ours["lat"], bus["lat"], "bus {id}");
        assert_eq!(ours["status"], bus["status"], "bus {id}");
    }
    // Loads match in power, model enum, and nominal voltage.
    for (id, load) in reference["load"].as_object().unwrap() {
        let ours = &emitted["load"][id];
        assert_eq!(ours["pd_nom"], load["pd_nom"], "load {id}");
        assert_eq!(ours["qd_nom"], load["qd_nom"], "load {id}");
        assert_eq!(ours["model"], load["model"], "load {id}");
        assert_eq!(ours["vm_nom"], load["vm_nom"], "load {id}");
        assert_eq!(ours["configuration"], load["configuration"], "load {id}");
        assert_eq!(ours["connections"], load["connections"], "load {id}");
    }
    // The switch reproduces PMD's tiny series resistance convention.
    assert_eq!(
        emitted["switch"]["671692"]["rs"],
        reference["switch"]["671692"]["rs"]
    );
    assert_eq!(
        emitted["switch"]["671692"]["state"],
        reference["switch"]["671692"]["state"]
    );
    // The voltage source Thevenin matrices match the engine's computation.
    let ours_rs = emitted["voltage_source"]["source"]["rs"]
        .as_array()
        .unwrap();
    let ref_rs = reference["voltage_source"]["source"]["rs"]
        .as_array()
        .unwrap();
    for (a, b) in ours_rs.iter().zip(ref_rs) {
        for (x, y) in a.as_array().unwrap().iter().zip(b.as_array().unwrap()) {
            assert!((x.as_f64().unwrap() - y.as_f64().unwrap()).abs() < 1e-9);
        }
    }
    // Transformer per unit impedances and taps match (sub: delta primary).
    for id in ["sub", "xfm1"] {
        let ours = &emitted["transformer"][id];
        let want = &reference["transformer"][id];
        assert_eq!(ours["rw"], want["rw"], "{id}");
        assert_eq!(ours["xsc"], want["xsc"], "{id}");
        assert_eq!(ours["vm_nom"], want["vm_nom"], "{id}");
        assert_eq!(ours["sm_nom"], want["sm_nom"], "{id}");
        assert_eq!(ours["polarity"], want["polarity"], "{id}");
        assert_eq!(ours["connections"], want["connections"], "{id}");
        assert_eq!(ours["tm_step"], want["tm_step"], "{id}");
    }
}

#[test]
fn null_suffix_restoration() {
    let text = r#"{
        "data_model": "ENGINEERING",
        "bus": {"a": {"terminals": [1], "grounded": [], "rg": [], "xg": [], "status": "ENABLED"}},
        "linecode": {"c": {"rs": [[1.0]], "xs": [[1.0]],
            "g_fr": [[0.0]], "g_to": [[0.0]], "b_fr": [[0.0]], "b_to": [[0.0]],
            "cm_ub": [null]}},
        "voltage_source": {"src": {"bus": "a", "connections": [1],
            "vm": [0.24], "va": [0.0], "status": "ENABLED"}}
    }"#;
    let net = parse_pmd_str(text).unwrap();
    // cm_ub null restores to +Inf under the `_ub` suffix; an infinite
    // ampacity bound means no bound, so i_max is None.
    assert!(net.linecodes[0].i_max.is_none());
}
