//! C ABI for `powerio`: ABI v4.
//!
//! Parse any supported power system case format into an opaque handle, query
//! it, convert it to another format, and pull out the numeric tables a
//! downstream solver needs to assemble matrices. Every entry point is
//! `extern "C"`, catches panics at the boundary, and returns error text into a
//! caller-provided buffer.
//!
//! The surface follows a fixed grammar, written out in the header preamble
//! (`include/powerio.h`, generated by cbindgen, never hand-edit):
//!
//! - Verb-led names are operations and the verb fixes the return family:
//!   `parse`/`read`/`normalize` return a new handle, `write` has a filesystem
//!   effect, `convert` transcodes without keeping a handle, `free` destroys.
//! - `to_` marks a representation change of the same network; the target is a
//!   format string (`pio_to_format`) unless the output type differs
//!   (`pio_to_arrow` fills Arrow C Data Interface structs).
//! - Format names never appear in symbols: formats are strings, so a new
//!   format never changes this ABI. The canonical snapshot is the
//!   `powerio-json` format name.
//! - Array extractors share the cap/count convention: write up to `cap`
//!   values, return the total available, `NULL` out is a pure count query.
//! - Vocabulary: a *bus* is a named connection point (this surface is bus
//!   granular); a *node* is one conductor's point at a bus, reserved for the
//!   multiconductor surface; a *branch* is any two-terminal series element,
//!   lines and transformers alike.

#![allow(clippy::missing_safety_doc)]

use std::ffi::{CStr, CString, c_char};
use std::panic::{AssertUnwindSafe, catch_unwind};

use powerio::{IndexCore, IndexedNetwork, Network, TargetFormat};

#[cfg(feature = "arrow")]
mod arrow_export;
#[cfg(feature = "arrow")]
pub use arrow_export::{
    PIO_ARROW_TABLE_BRANCH, PIO_ARROW_TABLE_BUS, PIO_ARROW_TABLE_GEN, PIO_ARROW_TABLE_LOAD,
    PIO_ARROW_TABLE_SHUNT,
};

/// Opaque parsed network handle. Carries the parsed [`Network`], the
/// [`IndexCore`] derived from it once at parse time (so every indexed query
/// reuses the same bus-id map and per-bus aggregates instead of rebuilding
/// them), and the reader's fidelity warnings ([`pio_warnings`]).
pub struct PioNetwork {
    net: Network,
    core: IndexCore,
    warnings: Vec<String>,
}

// The handle is immutable after construction and the C ABI documents concurrent
// reads from any number of threads as safe (see the cbindgen header preamble).
// That guarantee requires `PioNetwork: Send + Sync`; pin it at compile time so
// a future field that is not `Sync` fails the build instead of weakening it.
const _: fn() = || {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<PioNetwork>();
};

/// Copy `msg` (truncated to fit) into a caller `char[len]` buffer, always
/// NUL-terminated. Truncation backs up to a UTF-8 character boundary so a
/// clipped message is still valid UTF-8. Shared by the error and warning
/// outputs.
///
/// # Safety
/// A non-NULL `buf` must point to at least `len` writable bytes; the write
/// stays within `len` (at most `len - 1` message bytes plus the terminating
/// NUL). NULL or `len == 0` is a no-op.
unsafe fn copy_to_buf(buf: *mut c_char, len: usize, msg: &str) {
    unsafe {
        if buf.is_null() || len == 0 {
            return;
        }
        let bytes = msg.as_bytes();
        let mut n = bytes.len().min(len - 1);
        while n > 0 && !msg.is_char_boundary(n) {
            n -= 1;
        }
        std::ptr::copy_nonoverlapping(bytes.as_ptr().cast::<c_char>(), buf, n);
        *buf.add(n) = 0;
    }
}

unsafe fn cstr<'a>(p: *const c_char) -> Option<&'a str> {
    unsafe {
        if p.is_null() {
            return None;
        }
        CStr::from_ptr(p).to_str().ok()
    }
}

/// Move `s` into an owned C string, or `None` if it holds an interior NUL byte
/// (which can't cross as a C string). Callers surface the `None` as a real error
/// rather than silently handing back an empty string.
fn into_cstring(s: String) -> Option<*mut c_char> {
    CString::new(s).ok().map(CString::into_raw)
}

/// Finish a `*mut c_char` entry point: hand back the owned C string, or on an
/// interior NUL write the error into `errbuf` (NULL/0 to skip) and return NULL.
/// The shared tail of the string-returning functions.
fn finish_cstring(s: String, errbuf: *mut c_char, errlen: usize) -> *mut c_char {
    match into_cstring(s) {
        Some(p) => p,
        None => {
            unsafe { copy_to_buf(errbuf, errlen, "output contained an interior NUL byte") };
            std::ptr::null_mut()
        }
    }
}

/// Run `f` at the FFI boundary, catching any panic so it can't unwind across
/// `extern "C"` (UB). Returns `fallback` if `f` panics.
unsafe fn guard<R>(fallback: R, f: impl FnOnce() -> R) -> R {
    catch_unwind(AssertUnwindSafe(f)).unwrap_or(fallback)
}

/// Box a `Network` into an owned network handle, building its [`IndexCore`] once so
/// every indexed query reuses it. The one constructor for `*mut PioNetwork`.
fn make_network(net: Network, warnings: Vec<String>) -> *mut PioNetwork {
    let core = IndexCore::build(&net);
    Box::into_raw(Box::new(PioNetwork {
        net,
        core,
        warnings,
    }))
}

/// Finish a `*mut PioNetwork` entry point: run `f` (producing a `Network` with
/// its read warnings, or an error message) under the panic guard, hand back an
/// owned handle, or write the error, `panic_msg` if `f` panicked, into `errbuf`
/// and return NULL. The shared tail of every handle-returning function
/// (`pio_parse_file`, `pio_parse_str`, `pio_read_dir`, `pio_normalize`).
unsafe fn finish_network(
    errbuf: *mut c_char,
    errlen: usize,
    panic_msg: &str,
    f: impl FnOnce() -> Result<(Network, Vec<String>), String>,
) -> *mut PioNetwork {
    unsafe {
        match catch_unwind(AssertUnwindSafe(f)) {
            Ok(Ok((net, warnings))) => make_network(net, warnings),
            Ok(Err(msg)) => {
                copy_to_buf(errbuf, errlen, &msg);
                std::ptr::null_mut()
            }
            Err(_) => {
                copy_to_buf(errbuf, errlen, panic_msg);
                std::ptr::null_mut()
            }
        }
    }
}

/// ABI version of this C interface. Bump on any breaking change to an existing
/// `pio_*` signature or to the `powerio-json` snapshot schema (new additive
/// symbols don't require a bump). A consumer compares [`pio_abi_version`]
/// against the value it was built against (the `PIO_ABI_VERSION` macro in
/// `powerio.h`) and refuses a mismatched library instead of calling in blind.
///
/// v4 froze the naming grammar and conventions (see the header preamble); the
/// surface evolves additively from here: new data means new symbols, and rich
/// or multiconductor data rides the Arrow and `powerio-json` schemas, which
/// carry their own structure and never force a signature change.
pub const PIO_ABI_VERSION: u32 = 4;

/// ABI version of the optional `pio_dist_*` C surface. This is separate from
/// [`PIO_ABI_VERSION`] so distribution C entry points can evolve without forcing
/// a core ABI bump. Version 1 is the supported dist surface with conversion
/// order `(input, from, to, ...)`.
#[cfg(feature = "dist")]
pub const PIO_DIST_ABI_VERSION: u32 = 1;

/// A comfortable error-buffer size: pass a `char[PIO_ERRBUF_MIN]` to any
/// `errbuf`/`warnbuf` parameter and a message always fits without truncation.
pub const PIO_ERRBUF_MIN: usize = 256;

/// The ABI version the library was built with (see [`PIO_ABI_VERSION`]). Lets a
/// consumer detect a stale or incompatible library at load time. Infallible.
#[unsafe(no_mangle)]
pub extern "C" fn pio_abi_version() -> u32 {
    PIO_ABI_VERSION
}

/// The ABI version of the optional `pio_dist_*` surface. Only linked when the
/// `dist` feature is compiled in; probe that first with `pio_has_feature("dist")`
/// if loading dynamically.
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub extern "C" fn pio_dist_abi_version() -> u32 {
    PIO_DIST_ABI_VERSION
}

/// Whether an optional build feature is compiled in: pass `"arrow"`, `"gridfm"`,
/// or `"dist"`. Returns 1 if present, 0 otherwise (and 0 for a NULL or unknown
/// name). The optional surfaces (`pio_to_arrow`, the `pio_read_dir`/gridfm path,
/// the `pio_dist_*` block) are only linked when their feature is built, so a
/// consumer that loaded the library at runtime probes for them here instead of
/// resolving symbols blind. Feature names are strings — like format names, a new
/// feature never changes this signature. Infallible.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_has_feature(feature: *const c_char) -> i32 {
    unsafe {
        guard(0, || {
            let Some(name) = cstr(feature) else { return 0 };
            let features: &[(&str, bool)] = &[
                ("arrow", cfg!(feature = "arrow")),
                ("gridfm", cfg!(feature = "gridfm")),
                ("dist", cfg!(feature = "dist")),
            ];
            i32::from(features.iter().any(|&(n, on)| n == name && on))
        })
    }
}

/// The crate version string (a semver string), `'static` and NUL-terminated. Do
/// NOT free it. Informational; pair it with [`pio_abi_version`] for the actual
/// compatibility check.
#[unsafe(no_mangle)]
pub extern "C" fn pio_version() -> *const c_char {
    // env! is resolved at compile time; the trailing NUL makes it a valid C
    // string and the 'static lifetime means the pointer is always valid and
    // never owned by the caller.
    concat!(env!("CARGO_PKG_VERSION"), "\0")
        .as_ptr()
        .cast::<c_char>()
}

fn target_format_from_c(to: *const c_char) -> Result<TargetFormat, String> {
    let to = unsafe { cstr(to) }.ok_or_else(|| "to is NULL or not UTF-8".to_string())?;
    to.parse::<TargetFormat>().map_err(|e| e.to_string())
}

fn optional_cstr<'a>(p: *const c_char, name: &str) -> Result<Option<&'a str>, String> {
    if p.is_null() {
        Ok(None)
    } else {
        unsafe { cstr(p) }
            .map(Some)
            .ok_or_else(|| format!("{name} is not UTF-8"))
    }
}

/// Parse `path` (format from extension, or `from` if non-NULL) into a network
/// handle. `from` accepts the [`pio_parse_str`] format names plus
/// `pypsa-csv`/`pypsa` and `pwb`; that includes `pslf`/`epc`, and `.epc` is
/// inferred by extension. A PyPSA CSV folder is a directory, so it can only
/// enter through this function, with `from = "pypsa-csv"` (or NULL when the
/// directory holds a `network.csv`). Read fidelity warnings attach to the
/// handle ([`pio_warnings`]). Returns `NULL` on error and writes the message
/// into `errbuf`. Free the handle with [`pio_network_free`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_parse_file(
    path: *const c_char,
    from: *const c_char,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut PioNetwork {
    unsafe {
        finish_network(errbuf, errlen, "panic while parsing", || {
            let path = cstr(path).ok_or_else(|| "path is NULL or not UTF-8".to_string())?;
            let from = optional_cstr(from, "from")?;
            powerio::parse_file(std::path::Path::new(path), from)
                .map(|p| (p.network, p.warnings))
                .map_err(|e| e.to_string())
        })
    }
}

/// Parse in-memory case `text` of the named `format` into a network handle.
/// Unlike [`pio_parse_file`] there is no path to infer from, so `format` is
/// required: one of `matpower`/`m`, `powermodels`/`pm`, `egret`,
/// `pandapower-json`/`pandapower`/`pp`, `psse`/`raw`, `powerworld`/`aux`,
/// `pslf`/`epc`, or `powerio-json`/`json` (the canonical snapshot
/// [`pio_to_format`] writes, validated on read). PyPSA CSV folders are
/// directories, not text; parse them with [`pio_parse_file`] and
/// `from = "pypsa-csv"`. Read fidelity warnings attach to the handle
/// ([`pio_warnings`]). Returns `NULL` on error and writes the message into
/// `errbuf`. Free the handle with [`pio_network_free`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_parse_str(
    text: *const c_char,
    format: *const c_char,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut PioNetwork {
    unsafe {
        finish_network(errbuf, errlen, "panic while parsing", || {
            let text = cstr(text).ok_or_else(|| "text is NULL or not UTF-8".to_string())?;
            let format = cstr(format).ok_or_else(|| "format is NULL or not UTF-8".to_string())?;
            powerio::parse_str(text, format)
                .map(|p| (p.network, p.warnings))
                .map_err(|e| e.to_string())
        })
    }
}

/// Read one scenario of a dataset directory in the named `from` format into a
/// network handle: the directory sibling of [`pio_parse_file`]. `gridfm` (the
/// gridfm-datakit Parquet layout; `dir` resolves leniently: the `raw/` leaf,
/// a `<case>/` directory with a `raw/` child, or a parent holding exactly one
/// such case) is the one dataset format today. `scenario` selects within a
/// multi-scenario dataset ([`pio_scenario_ids`] enumerates them); formats
/// without scenarios take `0`. Read fidelity warnings attach to the handle
/// ([`pio_warnings`]). Returns `NULL` on error and writes the message into
/// `errbuf`. Free the handle with [`pio_network_free`]. Built
/// `--features gridfm`.
#[cfg(feature = "gridfm")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_read_dir(
    dir: *const c_char,
    from: *const c_char,
    scenario: i64,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut PioNetwork {
    unsafe {
        finish_network(errbuf, errlen, "panic while reading dataset", || {
            let dir = cstr(dir).ok_or_else(|| "dir is NULL or not UTF-8".to_string())?;
            let from = cstr(from).ok_or_else(|| "from is NULL or not UTF-8".to_string())?;
            powerio_matrix::read_dataset_dir(std::path::Path::new(dir), from, scenario)
                .map(|read| (read.network, read.warnings))
                .map_err(|e| e.to_string())
        })
    }
}

/// Write the distinct scenario ids (ascending) of the dataset directory `dir`
/// in the named `from` format into `out`, up to `cap` entries, and return the
/// total count: the cap/count convention of [`pio_bus_ids`]. `gridfm` is the
/// one dataset format today. Returns `-1` on error and writes the message into
/// `errbuf` (unlike the handle extractors, this reads the filesystem and can
/// fail). Built `--features gridfm`.
#[cfg(feature = "gridfm")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_scenario_ids(
    dir: *const c_char,
    from: *const c_char,
    out: *mut i64,
    cap: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> isize {
    unsafe {
        let r = catch_unwind(AssertUnwindSafe(|| {
            let dir = cstr(dir).ok_or_else(|| "dir is NULL or not UTF-8".to_string())?;
            let from = cstr(from).ok_or_else(|| "from is NULL or not UTF-8".to_string())?;
            powerio_matrix::dataset_scenario_ids(std::path::Path::new(dir), from)
                .map_err(|e| e.to_string())
        }));
        match r {
            Ok(Ok(ids)) => {
                let Ok(total) = isize::try_from(ids.len()) else {
                    copy_to_buf(errbuf, errlen, "scenario count exceeds isize");
                    return -1;
                };
                fill(out, cap, ids.iter().copied());
                total
            }
            Ok(Err(msg)) => {
                copy_to_buf(errbuf, errlen, &msg);
                -1
            }
            Err(_) => {
                copy_to_buf(errbuf, errlen, "panic while reading scenario ids");
                -1
            }
        }
    }
}

/// The fidelity warnings attached to the handle at construction (by whichever
/// of [`pio_parse_file`], [`pio_parse_str`], [`pio_read_dir`], or
/// [`pio_normalize`] built it), `\n`-joined into `warnbuf` (truncated to fit
/// on a UTF-8 boundary; NULL/0 to skip). Returns the byte length of the full
/// joined text, excluding the NUL; call once with `(NULL, 0)` to size, then
/// pass a `char[len + 1]`. `0` means no warnings (or a NULL handle); readers
/// that are total attach none.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_warnings(
    net: *const PioNetwork,
    warnbuf: *mut c_char,
    warnlen: usize,
) -> usize {
    unsafe {
        guard(0, || {
            let Some(c) = network_ref(net) else { return 0 };
            let msg = c.warnings.join("\n");
            copy_to_buf(warnbuf, warnlen, &msg);
            msg.len()
        })
    }
}

/// Free a network handle from [`pio_parse_file`], [`pio_parse_str`],
/// [`pio_read_dir`], or [`pio_normalize`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_network_free(net: *mut PioNetwork) {
    unsafe {
        // Under the same panic guard as every other entry point: the drop is
        // pure deallocation today, but "catches panics" must not depend on that
        // staying true.
        guard((), || {
            if !net.is_null() {
                drop(Box::from_raw(net));
            }
        });
    }
}

unsafe fn network_ref<'a>(net: *const PioNetwork) -> Option<&'a PioNetwork> {
    unsafe { net.as_ref() }
}

/// View `net` through its cached [`IndexCore`] with no per-call rebuild.
unsafe fn view<'a>(net: *const PioNetwork) -> Option<IndexedNetwork<'a>> {
    unsafe {
        net.as_ref()
            .map(|c| IndexedNetwork::with_core(&c.net, &c.core))
    }
}

/// Normalize `net` into a NEW network handle: per unit, radians, out-of-service
/// filtered, source bus ids preserved, bus types canonicalized (see
/// `Network::to_normalized`). A value transform, not a serialization, hence
/// the verb, while the `to_*` family re-encodes unchanged data. The result is
/// independent of `net`; free both with [`pio_network_free`]. Every extractor
/// and serializer works on it unchanged (the handle is per unit, not MW).
/// Returns `NULL` on error (no reference bus can be chosen, or a non-positive
/// base MVA) and writes the message into `errbuf`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_normalize(
    net: *const PioNetwork,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut PioNetwork {
    unsafe {
        finish_network(errbuf, errlen, "panic while normalizing", || {
            let c = network_ref(net).ok_or_else(|| "network handle is NULL".to_string())?;
            c.net
                .to_normalized()
                .map(|n| (n, c.warnings.clone()))
                .map_err(|e| e.to_string())
        })
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_n_buses(net: *const PioNetwork) -> usize {
    unsafe { guard(0, || network_ref(net).map_or(0, |c| c.net.buses.len())) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_n_branches(net: *const PioNetwork) -> usize {
    unsafe { guard(0, || network_ref(net).map_or(0, |c| c.net.branches.len())) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_n_gens(net: *const PioNetwork) -> usize {
    unsafe { guard(0, || network_ref(net).map_or(0, |c| c.net.generators.len())) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_base_mva(net: *const PioNetwork) -> f64 {
    unsafe { guard(0.0, || network_ref(net).map_or(0.0, |c| c.net.base_mva)) }
}

/// Dense `[0, n)` index of the single reference (slack) bus, or `-1` if not
/// exactly one. An INDEX into the [`pio_bus_ids`] ordering, not a bus id;
/// `pio_branches` from/to carry ids, so the unit is in the name. A network may
/// carry several references (one per island, or a normalized case that kept
/// the file's multiple `REF` buses); [`pio_ref_bus_indices`] reads them all,
/// and its count (`NULL` out) tells zero from many.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_ref_bus_index(net: *const PioNetwork) -> i64 {
    unsafe {
        guard(-1, || match view(net) {
            Some(v) => v
                .reference_bus_index()
                .map_or(-1, |i| i64::try_from(i).unwrap_or(-1)),
            None => -1,
        })
    }
}

/// Write the dense `[0, n)` indices of the reference (slack) buses, ascending,
/// into `out`, up to `cap` entries, and return the total count: the cap/count
/// convention of [`pio_bus_ids`]. `0` means none; `> 1` means one reference
/// per island or several fixed references in one island (a normalized case
/// always reports `>= 1`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_ref_bus_indices(
    net: *const PioNetwork,
    out: *mut i64,
    cap: usize,
) -> usize {
    unsafe {
        guard(0, || {
            view(net).map_or(0, |v| {
                fill(
                    out,
                    cap,
                    v.reference_bus_indices()
                        .into_iter()
                        .map(|i| i64::try_from(i).unwrap_or(-1)),
                )
            })
        })
    }
}

/// Number of islands: connected components of the in-service topology.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_n_islands(net: *const PioNetwork) -> usize {
    unsafe { guard(0, || view(net).map_or(0, |v| v.n_connected_components())) }
}

/// `1` if the in-service topology is radial (every island a tree), else `0`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_is_radial(net: *const PioNetwork) -> i32 {
    unsafe { guard(0, || view(net).map_or(0, |v| i32::from(v.is_radial()))) }
}

/// Serialize `net` to the named format `to`: the one text serializer; every
/// format is named by a string. Accepts the [`pio_parse_str`] names:
/// `matpower` is a byte-exact echo when the handle was parsed from MATPOWER,
/// and `powerio-json` is the canonical snapshot (validated by [`pio_parse_str`]
/// on the way back; the retained source text is the one field it omits). The
/// snapshot is lossless except for a non-finite `f64` (`Inf`/`NaN`), which JSON
/// cannot represent: it is written as `null`, named in a fidelity warning, and
/// then fails to read back; pass `warnbuf` to detect it.
///
/// Returns the text as an owned C string (free with [`pio_string_free`]),
/// `NULL` on error (message into `errbuf`). Fidelity warnings, if any, are
/// written `\n`-joined into `warnbuf`; a returned string has no handle to
/// attach them to.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_to_format(
    net: *const PioNetwork,
    to: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut c_char {
    unsafe {
        finish_conversion(warnbuf, warnlen, errbuf, errlen, || {
            let c = network_ref(net).ok_or_else(|| "network handle is NULL".to_string())?;
            let target = target_format_from_c(to)?;
            let conv = c.net.to_format(target).map_err(|e| e.to_string())?;
            Ok((conv.text, conv.warnings))
        })
    }
}

/// Finish a text-conversion entry point: run `f` (producing the converted text
/// with its fidelity warnings, or an error message) under the panic guard,
/// write the warnings into `warnbuf`, and hand back the owned C string, or
/// write the error and return NULL. The shared tail of [`pio_to_format`],
/// [`pio_convert_file`], and [`pio_convert_str`], mirroring [`finish_network`].
unsafe fn finish_conversion(
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
    f: impl FnOnce() -> Result<(String, Vec<String>), String>,
) -> *mut c_char {
    unsafe {
        match catch_unwind(AssertUnwindSafe(f)) {
            Ok(Ok((text, warnings))) => {
                copy_to_buf(warnbuf, warnlen, &warnings.join("\n"));
                finish_cstring(text, errbuf, errlen)
            }
            Ok(Err(msg)) => {
                copy_to_buf(errbuf, errlen, &msg);
                std::ptr::null_mut()
            }
            Err(_) => {
                copy_to_buf(errbuf, errlen, "panic while converting");
                std::ptr::null_mut()
            }
        }
    }
}

/// Convert the case file at `path` from format `from` (NULL to infer from the
/// path, as [`pio_parse_file`]) to format `to`, without keeping a handle.
/// Returns the converted text as an owned C string (free with
/// [`pio_string_free`]), `NULL` on error. Fidelity warnings, read side first,
/// are written `\n`-joined into `warnbuf`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_convert_file(
    path: *const c_char,
    from: *const c_char,
    to: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut c_char {
    unsafe {
        finish_conversion(warnbuf, warnlen, errbuf, errlen, || {
            let path = cstr(path).ok_or_else(|| "path is NULL or not UTF-8".to_string())?;
            let from = optional_cstr(from, "from")?;
            let target = target_format_from_c(to)?;
            let conv = powerio::convert_file(std::path::Path::new(path), target, from)
                .map_err(|e| e.to_string())?;
            Ok((conv.text, conv.warnings))
        })
    }
}

/// Convert in-memory case `text` from format `from` (required; there is no
/// path to infer from) to format `to`, without keeping a handle: the in-memory
/// sibling of [`pio_convert_file`]. Returns the converted text as an owned C
/// string (free with [`pio_string_free`]), `NULL` on error. Fidelity warnings,
/// read side first, are written `\n`-joined into `warnbuf`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_convert_str(
    text: *const c_char,
    from: *const c_char,
    to: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut c_char {
    unsafe {
        finish_conversion(warnbuf, warnlen, errbuf, errlen, || {
            let text = cstr(text).ok_or_else(|| "text is NULL or not UTF-8".to_string())?;
            let from = cstr(from).ok_or_else(|| "from is NULL or not UTF-8".to_string())?;
            let target = target_format_from_c(to)?;
            let conv = powerio::convert_str(text, target, from).map_err(|e| e.to_string())?;
            Ok((conv.text, conv.warnings))
        })
    }
}

/// Write `net` into the directory `out_dir` as the named directory-shaped
/// format `to`: the directory sibling of [`pio_to_format`]. PyPSA CSV
/// (`pypsa-csv`/`pypsa`) is the one such format today; a text format name is
/// an error pointing back at [`pio_to_format`]. Returns `0` on success and
/// `-1` on error (message into `errbuf`). Fidelity warnings, if any, are
/// written `\n`-joined into `warnbuf`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_write_dir(
    net: *const PioNetwork,
    to: *const c_char,
    out_dir: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> i32 {
    unsafe {
        let r = catch_unwind(AssertUnwindSafe(|| {
            let c = network_ref(net).ok_or_else(|| "network handle is NULL".to_string())?;
            let to = cstr(to).ok_or_else(|| "to is NULL or not UTF-8".to_string())?;
            let out_dir =
                cstr(out_dir).ok_or_else(|| "out_dir is NULL or not UTF-8".to_string())?;
            powerio::write_dir(&c.net, to, std::path::Path::new(out_dir)).map_err(|e| e.to_string())
        }));
        match r {
            Ok(Ok(warnings)) => {
                copy_to_buf(warnbuf, warnlen, &warnings.join("\n"));
                0
            }
            Ok(Err(msg)) => {
                copy_to_buf(errbuf, errlen, &msg);
                -1
            }
            Err(_) => {
                copy_to_buf(errbuf, errlen, "panic while writing directory");
                -1
            }
        }
    }
}

/// Free a string returned by [`pio_to_format`], [`pio_convert_file`], or
/// [`pio_convert_str`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_string_free(s: *mut c_char) {
    unsafe {
        // Same rationale as `pio_network_free`: the boundary catches panics.
        guard((), || {
            if !s.is_null() {
                drop(CString::from_raw(s));
            }
        });
    }
}

/// Write up to `cap` values from `vals` into `out` and return the total number
/// available. A NULL `out` skips the write, so `(NULL, 0)` is the pure count
/// query of the cap/count convention every array extractor shares.
unsafe fn fill<T: Copy>(out: *mut T, cap: usize, vals: impl ExactSizeIterator<Item = T>) -> usize {
    unsafe {
        let total = vals.len();
        if !out.is_null() {
            for (i, v) in vals.take(cap).enumerate() {
                *out.add(i) = v;
            }
        }
        total
    }
}

/// Write the 1-based external bus ids, in dense order, into `out`, up to `cap`
/// entries, and return the total bus count. This ordering DEFINES the dense
/// index space every other per-bus array shares. Call once with `(NULL, 0)` to
/// size, allocate, then call again to fill. Ids are int64 in `1..2^63-1` (a v4
/// invariant); a source id that is a string or exceeds that range is mapped to
/// dense int64 at read, never passed through raw.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_bus_ids(net: *const PioNetwork, out: *mut i64, cap: usize) -> usize {
    unsafe {
        guard(0, || {
            network_ref(net).map_or(0, |c| {
                fill(
                    out,
                    cap,
                    c.net
                        .buses
                        .iter()
                        .map(|b| i64::try_from(b.id.0).unwrap_or(-1)),
                )
            })
        })
    }
}

/// Write the branch table as parallel arrays, each up to `cap` entries, and
/// return the total branch count. A branch is any two-terminal series element
/// lines and transformers alike (a transformer has `tap != 0`). `from`/`to`
/// are 1-based bus IDS (the [`pio_bus_ids`] id space, not dense indices); map
/// them to dense matrix rows with the [`pio_bus_ids`] ordering. Any output
/// pointer may be NULL to skip that column; all NULL is the count query.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_branches(
    net: *const PioNetwork,
    from: *mut i64,
    to: *mut i64,
    r: *mut f64,
    x: *mut f64,
    b: *mut f64,
    tap: *mut f64,
    shift: *mut f64,
    in_service: *mut u8,
    cap: usize,
) -> usize {
    unsafe {
        guard(0, || {
            let Some(c) = network_ref(net) else { return 0 };
            let net = &c.net;
            fill(
                from,
                cap,
                net.branches
                    .iter()
                    .map(|br| i64::try_from(br.from.0).unwrap_or(-1)),
            );
            fill(
                to,
                cap,
                net.branches
                    .iter()
                    .map(|br| i64::try_from(br.to.0).unwrap_or(-1)),
            );
            fill(r, cap, net.branches.iter().map(|br| br.r));
            fill(x, cap, net.branches.iter().map(|br| br.x));
            fill(b, cap, net.branches.iter().map(|br| br.b));
            fill(tap, cap, net.branches.iter().map(|br| br.tap));
            fill(shift, cap, net.branches.iter().map(|br| br.shift));
            fill(
                in_service,
                cap,
                net.branches.iter().map(|br| u8::from(br.in_service)),
            );
            net.branches.len()
        })
    }
}

/// Write the generator table as parallel arrays, each up to `cap` entries, and
/// return the total generator count. `bus` is the 1-based bus id (the
/// [`pio_bus_ids`] id space). Any output pointer may be NULL to skip.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_gens(
    net: *const PioNetwork,
    bus: *mut i64,
    pg: *mut f64,
    pmax: *mut f64,
    pmin: *mut f64,
    in_service: *mut u8,
    cap: usize,
) -> usize {
    unsafe {
        guard(0, || {
            let Some(c) = network_ref(net) else { return 0 };
            let net = &c.net;
            fill(
                bus,
                cap,
                net.generators
                    .iter()
                    .map(|g| i64::try_from(g.bus.0).unwrap_or(-1)),
            );
            fill(pg, cap, net.generators.iter().map(|g| g.pg));
            fill(pmax, cap, net.generators.iter().map(|g| g.pmax));
            fill(pmin, cap, net.generators.iter().map(|g| g.pmin));
            fill(
                in_service,
                cap,
                net.generators.iter().map(|g| u8::from(g.in_service)),
            );
            net.generators.len()
        })
    }
}

/// Write the per-bus demand aggregates (active `pd`, reactive `qd`, summed
/// over each bus's loads, dense [`pio_bus_ids`] order), each up to `cap`
/// entries, and return the total bus count. Either pointer may be NULL.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_bus_demand(
    net: *const PioNetwork,
    pd: *mut f64,
    qd: *mut f64,
    cap: usize,
) -> usize {
    unsafe {
        guard(0, || {
            view(net).map_or(0, |v| {
                // Return an explicit bus count, not the last fill's result, so the
                // cap/count return is independent of which columns were requested.
                let n = fill(pd, cap, v.pd().iter().copied());
                fill(qd, cap, v.qd().iter().copied());
                n
            })
        })
    }
}

/// Write the per-bus shunt aggregates (conductance `gs`, susceptance `bs`,
/// dense [`pio_bus_ids`] order), each up to `cap` entries, and return the
/// total bus count. Either pointer may be NULL.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_bus_shunt(
    net: *const PioNetwork,
    gs: *mut f64,
    bs: *mut f64,
    cap: usize,
) -> usize {
    unsafe {
        guard(0, || {
            view(net).map_or(0, |v| {
                // Explicit bus count, not the last fill's result (see pio_bus_demand).
                let n = fill(gs, cap, v.gs().iter().copied());
                fill(bs, cap, v.bs().iter().copied());
                n
            })
        })
    }
}

/// Export one raw network table over the Arrow C Data Interface: the `to_`
/// conversion whose output type is Arrow structs rather than a string, and the
/// bulk plane this ABI evolves on: new or richer columns arrive in the Arrow
/// schema, leaving the C signatures fixed.
///
/// `table` is one of the `PIO_ARROW_TABLE_*` selectors (bus/branch/gen/load/
/// shunt); the columns are the parsed network fields with EXTERNAL bus ids (the
/// `pio_bus_ids` id space), not the gridfm schema. On success (returns `0`),
/// `out_array` and `out_schema` are populated with owned C Data Interface
/// structs: ownership of the Arrow buffers transfers to the caller, both
/// `release` callbacks are non-NULL, and the caller MUST invoke each exactly
/// once when done (skipping one leaks; the structs outlive `pio_network_free`).
/// On error (returns `-1`) the message is written into `errbuf` and the
/// out-params are left untouched. Only built with the `arrow` cargo feature.
#[cfg(feature = "arrow")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_to_arrow(
    net: *const PioNetwork,
    table: i32,
    out_array: *mut arrow::ffi::FFI_ArrowArray,
    out_schema: *mut arrow::ffi::FFI_ArrowSchema,
    errbuf: *mut c_char,
    errlen: usize,
) -> i32 {
    unsafe {
        let r = catch_unwind(AssertUnwindSafe(|| {
            if out_array.is_null() || out_schema.is_null() {
                return Err("out_array or out_schema is NULL".to_string());
            }
            let c = network_ref(net).ok_or_else(|| "network handle is NULL".to_string())?;
            arrow_export::export(&c.net, table)
        }));
        match r {
            Ok(Ok((array, schema))) => {
                // Move the FFI structs into caller memory: ptr::write does not
                // drop the (caller-zeroed) destination and does not run Drop on
                // `array`/`schema`, so the producer release callbacks transfer to
                // the caller. Exactly one owner.
                std::ptr::write(out_array, array);
                std::ptr::write(out_schema, schema);
                0
            }
            Ok(Err(msg)) => {
                copy_to_buf(errbuf, errlen, &msg);
                -1
            }
            Err(_) => {
                copy_to_buf(errbuf, errlen, "panic while exporting Arrow");
                -1
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Distribution surface (`dist` feature). The multiconductor model behind its own
// opaque `PioDistNetwork` handle and the `pio_dist_*` entry points. It is gated
// on the `dist` feature / `PIO_DIST` define, exactly like `arrow`/`gridfm`; a
// runtime consumer probes it with `pio_has_feature("dist")`, then checks
// `pio_dist_abi_version()`. The surface is EXPERIMENTAL while the IEEE BMOPF
// schema is a draft: C signature changes bump `PIO_DIST_ABI_VERSION`, and the
// JSON payloads (bmopf-json, powerio-dist-json) carry their own meta.version.
// ---------------------------------------------------------------------------

/// Like [`cstr`] but a NULL or non-UTF-8 pointer is an error naming the offending
/// parameter. The dist entry points take mostly required strings.
#[cfg(feature = "dist")]
fn required_cstr<'a>(p: *const c_char, name: &str) -> Result<&'a str, String> {
    unsafe { cstr(p) }.ok_or_else(|| format!("{name} is NULL or not UTF-8"))
}

/// Finish a handle-returning dist entry point: run `f` (the handle payload or an
/// error message) under the panic guard and box the payload into an owned handle,
/// or write the error (`panic_msg` if `f` panicked) into `errbuf` and return NULL.
#[cfg(feature = "dist")]
unsafe fn finish_handle<H>(
    errbuf: *mut c_char,
    errlen: usize,
    panic_msg: &str,
    f: impl FnOnce() -> Result<H, String>,
) -> *mut H {
    unsafe {
        match catch_unwind(AssertUnwindSafe(f)) {
            Ok(Ok(h)) => Box::into_raw(Box::new(h)),
            Ok(Err(msg)) => {
                copy_to_buf(errbuf, errlen, &msg);
                std::ptr::null_mut()
            }
            Err(_) => {
                copy_to_buf(errbuf, errlen, panic_msg);
                std::ptr::null_mut()
            }
        }
    }
}

/// Opaque parsed distribution network handle (the multiconductor wire-coordinate
/// model). Distinct from [`PioNetwork`] (the positive-sequence transmission
/// model); none of the `pio_n_*`/extractor functions accept it. Only built with
/// the `dist` cargo feature.
#[cfg(feature = "dist")]
pub struct PioDistNetwork {
    net: powerio_dist::DistNetwork,
}

/// Parse a distribution case file into a [`PioDistNetwork`] handle. The format
/// comes from `from` if non-NULL (`dss`, `pmd`, or `bmopf`), else from the file
/// itself: `.dss` is OpenDSS, and `.json` holding the ENGINEERING `data_model`
/// key is PMD JSON, otherwise BMOPF JSON. Returns `NULL` on error and writes the
/// message into `errbuf`. Free the handle with [`pio_dist_network_free`].
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_parse_file(
    path: *const c_char,
    from: *const c_char,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut PioDistNetwork {
    unsafe {
        finish_handle(errbuf, errlen, "panic while parsing", || {
            let path = required_cstr(path, "path")?;
            let from = optional_cstr(from, "from")?;
            powerio_dist::parse_file(std::path::Path::new(path), from)
                .map(|net| PioDistNetwork { net })
                .map_err(|e| e.to_string())
        })
    }
}

/// Parse in-memory distribution case `text` of the named `format` (`dss`, `pmd`,
/// or `bmopf`; required, since there is no path to infer from). An OpenDSS
/// `Redirect`/`Compile` in `text` resolves against the current working directory.
/// Returns `NULL` on error and writes the message into `errbuf`. Free the handle
/// with [`pio_dist_network_free`].
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_parse_str(
    text: *const c_char,
    format: *const c_char,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut PioDistNetwork {
    unsafe {
        finish_handle(errbuf, errlen, "panic while parsing", || {
            let text = required_cstr(text, "text")?;
            let format = required_cstr(format, "format")?;
            powerio_dist::parse_str(text, format)
                .map(|net| PioDistNetwork { net })
                .map_err(|e| e.to_string())
        })
    }
}

/// Free a distribution network handle from [`pio_dist_parse_file`] or
/// [`pio_dist_parse_str`]. NULL is a no-op; free exactly once.
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_network_free(net: *mut PioDistNetwork) {
    unsafe {
        // Same rationale as `pio_network_free`: the boundary catches panics so a
        // Drop on the `serde_json::Value` extras can't unwind across the ABI.
        guard((), || {
            if !net.is_null() {
                drop(Box::from_raw(net));
            }
        });
    }
}

/// Parse warnings retained on the handle (everything the reader could not
/// represent or had to assume), `\n`-joined and written into the caller `warnbuf`
/// (truncated to fit, always NUL-terminated). Returns the total byte length of
/// the joined message; call with `NULL`/0 to size first, then fill — the same
/// idiom as [`pio_warnings`]. Returns 0 for a NULL handle.
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_warnings(
    net: *const PioDistNetwork,
    warnbuf: *mut c_char,
    warnlen: usize,
) -> usize {
    unsafe {
        guard(0, || {
            let Some(c) = net.as_ref() else { return 0 };
            let msg = c.net.warnings.join("\n");
            copy_to_buf(warnbuf, warnlen, &msg);
            msg.len()
        })
    }
}

/// Serialize `net` to distribution format `to` (`dss`, `pmd`, or `bmopf`).
/// Writing back to the format the handle was parsed from echoes the source text
/// byte for byte; a cross-format write reports every fidelity loss in `warnbuf`
/// (`\n`-joined). Returns the text as an owned C string (free with
/// [`pio_string_free`]), `NULL` on error.
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_to_format(
    net: *const PioDistNetwork,
    to: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut c_char {
    unsafe {
        finish_conversion(warnbuf, warnlen, errbuf, errlen, || {
            let c = net
                .as_ref()
                .ok_or_else(|| "network handle is NULL".to_string())?;
            let target = dist_target_from_c(to)?;
            let conv = c.net.to_format(target);
            Ok((conv.text, conv.warnings))
        })
    }
}

/// Convert distribution case `path` from optional source format `from` to format
/// `to`; see [`pio_dist_parse_file`] for the inference rules. Returns the
/// converted text as an owned C string (free with [`pio_string_free`]), `NULL` on
/// error. The warnings written `\n`-joined into `warnbuf` carry both the parse
/// warnings and the writer's fidelity losses (there is no handle to query them).
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_convert_file(
    path: *const c_char,
    from: *const c_char,
    to: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut c_char {
    unsafe {
        finish_conversion(warnbuf, warnlen, errbuf, errlen, || {
            let path = required_cstr(path, "path")?;
            dist_convert_file_compat(std::path::Path::new(path), from, to)
        })
    }
}

/// Convert in-memory distribution case `text` of format `from` to format `to`
/// (both required; `dss`, `pmd`, or `bmopf`). The parameter order is input,
/// source, target, matching [`pio_dist_convert_file`]. Returns the converted text
/// as an owned C string (free with [`pio_string_free`]), `NULL` on error. The
/// warnings written `\n`-joined into `warnbuf` carry both the parse warnings and
/// the writer's fidelity losses (there is no handle to query them).
#[cfg(feature = "dist")]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn pio_dist_convert_str(
    text: *const c_char,
    from: *const c_char,
    to: *const c_char,
    warnbuf: *mut c_char,
    warnlen: usize,
    errbuf: *mut c_char,
    errlen: usize,
) -> *mut c_char {
    unsafe {
        finish_conversion(warnbuf, warnlen, errbuf, errlen, || {
            let text = required_cstr(text, "text")?;
            dist_convert_str_compat(text, from, to)
        })
    }
}

#[cfg(feature = "dist")]
fn dist_convert_file_compat(
    path: &std::path::Path,
    from: *const c_char,
    to: *const c_char,
) -> Result<(String, Vec<String>), String> {
    let current: Result<(String, Vec<String>), String> = (|| {
        let from = optional_cstr(from, "from")?;
        let to = dist_target_from_c(to)?;
        let conv = powerio_dist::convert_file(path, to, from).map_err(|e| e.to_string())?;
        Ok((conv.text, conv.warnings))
    })();
    current.or_else(|primary| {
        let legacy: Result<(String, Vec<String>), String> = (|| {
            let legacy_to = dist_target_from_c(from)?;
            let legacy_from = optional_cstr(to, "from")?;
            let conv = powerio_dist::convert_file(path, legacy_to, legacy_from)
                .map_err(|e| e.to_string())?;
            Ok((conv.text, conv.warnings))
        })();
        legacy.map_err(|_| primary)
    })
}

#[cfg(feature = "dist")]
fn dist_convert_str_compat(
    text: &str,
    from: *const c_char,
    to: *const c_char,
) -> Result<(String, Vec<String>), String> {
    let current: Result<(String, Vec<String>), String> = (|| {
        let to = dist_target_from_c(to)?;
        let from = required_cstr(from, "from")?;
        let conv = powerio_dist::convert_str(text, to, from).map_err(|e| e.to_string())?;
        Ok((conv.text, conv.warnings))
    })();
    current.or_else(|primary| {
        let legacy: Result<(String, Vec<String>), String> = (|| {
            let legacy_to = dist_target_from_c(from)?;
            let legacy_from = required_cstr(to, "from")?;
            let conv = powerio_dist::convert_str(text, legacy_to, legacy_from)
                .map_err(|e| e.to_string())?;
            Ok((conv.text, conv.warnings))
        })();
        legacy.map_err(|_| primary)
    })
}

#[cfg(feature = "dist")]
fn dist_target_from_c(to: *const c_char) -> Result<powerio_dist::DistTargetFormat, String> {
    let to = required_cstr(to, "to")?;
    // The message comes from the real error so it can't drift from what the
    // powerio-dist dispatchers report for the same mistake.
    to.parse::<powerio_dist::DistTargetFormat>()
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    fn data_path(name: &str) -> CString {
        CString::new(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../tests/data")
                .join(name)
                .to_str()
                .unwrap(),
        )
        .unwrap()
    }

    fn case9() -> *mut PioNetwork {
        let path = data_path("case9.m");
        let mut err = [0 as c_char; 256];
        let c =
            unsafe { pio_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len()) };
        assert!(!c.is_null(), "parse returned null");
        c
    }

    /// `pio_to_format` with a Rust-side format name, asserting success.
    unsafe fn to_format(net: *const PioNetwork, to: &str) -> String {
        let to = CString::new(to).unwrap();
        let mut warn = [0 as c_char; 512];
        let mut err = [0 as c_char; 256];
        unsafe {
            let s = pio_to_format(
                net,
                to.as_ptr(),
                warn.as_mut_ptr(),
                warn.len(),
                err.as_mut_ptr(),
                err.len(),
            );
            assert!(
                !s.is_null(),
                "to_format failed: {}",
                CStr::from_ptr(err.as_ptr()).to_str().unwrap()
            );
            let text = CStr::from_ptr(s).to_str().unwrap().to_owned();
            pio_string_free(s);
            text
        }
    }

    #[test]
    fn version_surface() {
        // The ABI version is the load-time compatibility check; the version
        // string is static, NUL-terminated, and non-empty.
        assert_eq!(pio_abi_version(), PIO_ABI_VERSION);
        assert_eq!(PIO_ABI_VERSION, 4);
        let v = unsafe { CStr::from_ptr(pio_version()) }.to_str().unwrap();
        assert_eq!(v, env!("CARGO_PKG_VERSION"));
        assert!(!v.is_empty());
    }

    #[test]
    fn parse_query_free() {
        let c = case9();
        unsafe {
            assert_eq!(pio_n_buses(c), 9);
            assert_eq!(pio_n_branches(c), 9);
            assert_eq!(pio_n_gens(c), 3);
            assert_eq!(pio_base_mva(c), 100.0);
            assert_eq!(pio_n_islands(c), 1);
            assert!(pio_ref_bus_index(c) >= 0);
            // The MATPOWER reader is total: no warnings, zero bytes.
            assert_eq!(pio_warnings(c, std::ptr::null_mut(), 0), 0);
            pio_network_free(c);
        }
    }

    #[test]
    fn warnings_size_then_fill_exactly() {
        // The pandapower fixture carries switches the model ignores. The byte
        // length returned by the NULL-out call must size a buffer that then
        // receives the full text untruncated.
        let path = data_path("pandapower/example.json");
        let mut err = [0 as c_char; 256];
        let c =
            unsafe { pio_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len()) };
        assert!(
            !c.is_null(),
            "parse failed: {}",
            unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap()
        );
        unsafe {
            let len = pio_warnings(c, std::ptr::null_mut(), 0);
            assert!(len > 0, "expected read warnings");
            let mut warn = vec![0x7f as c_char; len + 1];
            assert_eq!(pio_warnings(c, warn.as_mut_ptr(), warn.len()), len);
            let w = CStr::from_ptr(warn.as_ptr()).to_str().unwrap();
            assert_eq!(w.len(), len, "buffer sized from the return holds it all");
            assert!(w.contains("switch"), "expected a switch warning, got {w:?}");
            // A NULL handle reports zero bytes.
            assert_eq!(
                pio_warnings(std::ptr::null(), warn.as_mut_ptr(), warn.len()),
                0
            );
            pio_network_free(c);
        }
    }

    #[test]
    fn matpower_write_is_byte_exact() {
        let src = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/data/case9.m"),
        )
        .unwrap();
        let c = case9();
        unsafe {
            assert_eq!(to_format(c, "matpower"), src);

            // A NULL handle is an error message, not a crash.
            let to = CString::new("matpower").unwrap();
            let mut err = [0 as c_char; 256];
            let null = pio_to_format(
                std::ptr::null(),
                to.as_ptr(),
                std::ptr::null_mut(),
                0,
                err.as_mut_ptr(),
                err.len(),
            );
            assert!(null.is_null());
            assert_eq!(
                CStr::from_ptr(err.as_ptr()).to_str().unwrap(),
                "network handle is NULL"
            );
            pio_network_free(c);
        }
    }

    #[test]
    fn extract_branch_tables() {
        let c = case9();
        unsafe {
            // All-NULL is the count query.
            let nb = pio_branches(
                c,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                0,
            );
            assert_eq!(nb, pio_n_branches(c));
            let mut from = vec![0i64; nb];
            let mut x = vec![0f64; nb];
            let total = pio_branches(
                c,
                from.as_mut_ptr(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                x.as_mut_ptr(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                nb,
            );
            assert_eq!(total, nb);
            // `from` carries the 1-based bus ids (case9 buses are 1..=9), the
            // same id space as pio_bus_ids, not dense indices.
            assert!(from.iter().all(|&f| f >= 1));
            assert!(x.iter().all(|&xx| xx > 0.0));
            pio_network_free(c);
        }
    }

    #[test]
    fn cap_clamps_the_write_and_returns_the_total() {
        let c = case9();
        unsafe {
            let total = pio_bus_ids(c, std::ptr::null_mut(), 0);
            assert_eq!(total, 9);
            // A two-slot buffer gets exactly two ids; the total still comes back,
            // so a short read is detectable.
            let mut ids = [-1i64; 2];
            assert_eq!(pio_bus_ids(c, ids.as_mut_ptr(), ids.len()), 9);
            assert!(ids.iter().all(|&id| id >= 1));
            pio_network_free(c);
        }
    }

    #[test]
    fn convert_matpower_echo() {
        let path = data_path("case14.m");
        let to = CString::new("matpower").unwrap();
        let mut warn = [0 as c_char; 256];
        let mut err = [0 as c_char; 256];
        unsafe {
            let s = pio_convert_file(
                path.as_ptr(),
                std::ptr::null(),
                to.as_ptr(),
                warn.as_mut_ptr(),
                warn.len(),
                err.as_mut_ptr(),
                err.len(),
            );
            assert!(!s.is_null());
            let got = CStr::from_ptr(s).to_str().unwrap();
            let src = std::fs::read_to_string(
                std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/data/case14.m"),
            )
            .unwrap();
            assert_eq!(got, src);
            pio_string_free(s);
        }
    }

    #[test]
    fn convert_str_round_trips_in_memory() {
        // The in-memory converter is parse_str + to_format fused: matpower in,
        // powermodels out, no filesystem.
        let src = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/data/case9.m"),
        )
        .unwrap();
        let text = CString::new(src).unwrap();
        let from = CString::new("matpower").unwrap();
        let to = CString::new("powermodels-json").unwrap();
        let mut warn = [0 as c_char; 512];
        let mut err = [0 as c_char; 256];
        unsafe {
            let s = pio_convert_str(
                text.as_ptr(),
                from.as_ptr(),
                to.as_ptr(),
                warn.as_mut_ptr(),
                warn.len(),
                err.as_mut_ptr(),
                err.len(),
            );
            assert!(
                !s.is_null(),
                "convert_str failed: {}",
                CStr::from_ptr(err.as_ptr()).to_str().unwrap()
            );
            let out = CStr::from_ptr(s).to_str().unwrap();
            assert!(out.contains("\"bus\""));
            pio_string_free(s);
        }
    }

    #[test]
    fn to_format_converts_live_handle() {
        let c = case9();
        unsafe {
            let text = to_format(c, "powermodels-json");
            assert!(text.contains("\"bus\""));
            pio_network_free(c);
        }
    }

    #[test]
    fn parse_error_sets_message_not_null_handle() {
        let path = CString::new("/no/such/case.m").unwrap();
        let mut err = [0 as c_char; 256];
        let c =
            unsafe { pio_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len()) };
        assert!(c.is_null());
        let msg = unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap();
        assert!(!msg.is_empty(), "expected an error message");
    }

    #[test]
    fn non_utf8_from_hint_errors_instead_of_falling_back() {
        let path = data_path("case9.m");
        let to = CString::new("matpower").unwrap();
        let bad_from = [0xff_u8, 0];
        let mut err = [0 as c_char; 256];
        let c = unsafe {
            pio_parse_file(
                path.as_ptr(),
                bad_from.as_ptr().cast::<c_char>(),
                err.as_mut_ptr(),
                err.len(),
            )
        };
        assert!(c.is_null());
        assert_eq!(
            unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap(),
            "from is not UTF-8"
        );

        let mut warn = [0 as c_char; 256];
        err.fill(0);
        let s = unsafe {
            pio_convert_file(
                path.as_ptr(),
                bad_from.as_ptr().cast::<c_char>(),
                to.as_ptr(),
                warn.as_mut_ptr(),
                warn.len(),
                err.as_mut_ptr(),
                err.len(),
            )
        };
        assert!(s.is_null());
        assert_eq!(
            unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap(),
            "from is not UTF-8"
        );
    }

    #[test]
    fn extract_gen_and_bus_aggregate_tables() {
        // case30 carries generators, loads, and shunts: cross-check the table
        // extractors against known counts and aggregate signs (a column swap in
        // pio_gens/pio_bus_* would otherwise ship silently).
        let path = data_path("case30.m");
        let mut err = [0 as c_char; 256];
        let c =
            unsafe { pio_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len()) };
        assert!(!c.is_null());
        unsafe {
            let nb = pio_n_buses(c);
            let ng = pio_n_gens(c);
            assert_eq!(nb, 30);
            assert!(ng > 0);

            let mut gbus = vec![-9i64; ng];
            let mut pmax = vec![0f64; ng];
            let total = pio_gens(
                c,
                gbus.as_mut_ptr(),
                std::ptr::null_mut(),
                pmax.as_mut_ptr(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                ng,
            );
            assert_eq!(total, ng);
            // Generator buses are 1-based ids within the case's id range.
            assert!(gbus.iter().all(|&b| (1..=nb as i64).contains(&b)));
            assert!(pmax.iter().any(|&p| p > 0.0));

            let mut ids = vec![0i64; nb];
            assert_eq!(pio_bus_ids(c, ids.as_mut_ptr(), nb), nb);
            assert!(ids.iter().all(|&id| id >= 1)); // MATPOWER bus ids are 1-based

            let mut pd = vec![0f64; nb];
            let mut qd = vec![0f64; nb];
            assert_eq!(pio_bus_demand(c, pd.as_mut_ptr(), qd.as_mut_ptr(), nb), nb);
            assert!(pd.iter().sum::<f64>() > 0.0, "case30 has active demand");

            let mut gs = vec![0f64; nb];
            let mut bs = vec![0f64; nb];
            assert_eq!(pio_bus_shunt(c, gs.as_mut_ptr(), bs.as_mut_ptr(), nb), nb);
            assert!(gs.iter().chain(bs.iter()).all(|x| x.is_finite()));

            pio_network_free(c);
        }
    }

    #[test]
    fn null_handle_and_null_out_are_safe() {
        // Every query tolerates a NULL handle (the documented safe default), and
        // a NULL output pointer on a valid case is a count query, not a deref.
        unsafe {
            let nil: *const PioNetwork = std::ptr::null();
            assert_eq!(pio_n_buses(nil), 0);
            assert_eq!(pio_n_branches(nil), 0);
            assert_eq!(pio_n_gens(nil), 0);
            assert_eq!(pio_base_mva(nil), 0.0);
            assert_eq!(pio_ref_bus_index(nil), -1);
            assert_eq!(pio_ref_bus_indices(nil, std::ptr::null_mut(), 0), 0);
            assert_eq!(pio_is_radial(nil), 0);
            assert_eq!(pio_n_islands(nil), 0);

            // The two FFI constructors reject a NULL input rather than crash.
            let mut err = [0 as c_char; 128];
            assert!(pio_normalize(nil, err.as_mut_ptr(), err.len()).is_null());
            let fmt = CString::new("matpower").unwrap();
            assert!(
                pio_parse_str(std::ptr::null(), fmt.as_ptr(), err.as_mut_ptr(), err.len())
                    .is_null()
            );

            let c = case9();
            assert_eq!(pio_bus_ids(c, std::ptr::null_mut(), 0), 9);
            pio_ref_bus_indices(c, std::ptr::null_mut(), 0);
            pio_bus_demand(c, std::ptr::null_mut(), std::ptr::null_mut(), 0);
            pio_gens(
                c,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                0,
            );
            pio_network_free(c);
        }
    }

    #[test]
    fn normalized_multi_ref_is_legible() {
        // A two-slack case (both gen-backed file REF buses) normalizes to a
        // handle that keeps both references. `pio_ref_bus_index` can't name a
        // single slack (returns -1), but the reference-set extractor does, so a
        // C consumer can tell "two slacks, you pick" from "no slack, broken".
        let src = "\
function mpc = tworef
mpc.version = '2';
mpc.baseMVA = 100;
mpc.bus = [
\t1\t3\t0\t0\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
\t2\t3\t0\t0\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
\t3\t1\t50\t10\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
];
mpc.gen = [
\t1\t0\t0\t100\t-100\t1\t100\t1\t100\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0;
\t2\t0\t0\t100\t-100\t1\t100\t1\t300\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0;
];
mpc.branch = [
\t1\t2\t0.01\t0.1\t0\t0\t0\t0\t0\t0\t1\t-360\t360;
\t2\t3\t0.01\t0.1\t0\t0\t0\t0\t0\t0\t1\t-360\t360;
];
";
        let text = CString::new(src).unwrap();
        let fmt = CString::new("matpower").unwrap();
        let mut err = [0 as c_char; 256];
        unsafe {
            let cs = pio_parse_str(text.as_ptr(), fmt.as_ptr(), err.as_mut_ptr(), err.len());
            assert!(!cs.is_null(), "parse_str returned null");
            let cn = pio_normalize(cs, err.as_mut_ptr(), err.len());
            assert!(!cn.is_null(), "normalize returned null");

            // Count via NULL out, then fill.
            assert_eq!(pio_ref_bus_indices(cn, std::ptr::null_mut(), 0), 2);
            // Multiple references: the single-slack query reports -1, by design.
            assert_eq!(pio_ref_bus_index(cn), -1);
            let mut refs = [-1i64; 2];
            assert_eq!(pio_ref_bus_indices(cn, refs.as_mut_ptr(), refs.len()), 2);
            assert_eq!(refs, [0, 1]);

            pio_network_free(cn);
            pio_network_free(cs);
        }
    }

    #[test]
    fn normalized_preserves_source_bus_ids() {
        let src = "\
function mpc = sparseids
mpc.version = '2';
mpc.baseMVA = 100;
mpc.bus = [
\t1\t3\t0\t0\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
\t2\t1\t0\t0\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
\t3\t1\t0\t0\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
\t4\t1\t0\t0\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
\t10\t1\t50\t10\t0\t0\t1\t1\t0\t230\t1\t1.1\t0.9;
];
mpc.gen = [
\t1\t0\t0\t100\t-100\t1\t100\t1\t200\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0;
];
mpc.branch = [
\t1\t2\t0.01\t0.1\t0\t0\t0\t0\t0\t0\t1\t-360\t360;
\t2\t3\t0.01\t0.1\t0\t0\t0\t0\t0\t0\t1\t-360\t360;
\t3\t4\t0.01\t0.1\t0\t0\t0\t0\t0\t0\t1\t-360\t360;
\t4\t10\t0.01\t0.1\t0\t0\t0\t0\t0\t0\t1\t-360\t360;
];
";
        let text = CString::new(src).unwrap();
        let fmt = CString::new("matpower").unwrap();
        let mut err = [0 as c_char; 256];
        unsafe {
            let cs = pio_parse_str(text.as_ptr(), fmt.as_ptr(), err.as_mut_ptr(), err.len());
            assert!(!cs.is_null(), "parse_str returned null");
            let cn = pio_normalize(cs, err.as_mut_ptr(), err.len());
            assert!(!cn.is_null(), "normalize returned null");

            let mut ids = vec![0i64; pio_n_buses(cn)];
            pio_bus_ids(cn, ids.as_mut_ptr(), ids.len());
            assert_eq!(ids, vec![1, 2, 3, 4, 10]);

            let mut from = vec![0i64; pio_n_branches(cn)];
            let mut to = vec![0i64; pio_n_branches(cn)];
            pio_branches(
                cn,
                from.as_mut_ptr(),
                to.as_mut_ptr(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                from.len(),
            );
            assert_eq!((from[3], to[3]), (4, 10));

            pio_network_free(cn);
            pio_network_free(cs);
        }
    }

    #[test]
    fn convert_emits_warning_into_buffer() {
        // t_case9_dcline carries an HVDC dcline. PSS/E writes it as two-terminal DC
        // but defaults the converter detail; that fidelity note must reach the
        // caller's warning buffer, not vanish.
        let path = data_path("t_case9_dcline.m");
        let to = CString::new("psse").unwrap();
        let mut warn = [0 as c_char; 512];
        let mut err = [0 as c_char; 256];
        unsafe {
            let s = pio_convert_file(
                path.as_ptr(),
                std::ptr::null(),
                to.as_ptr(),
                warn.as_mut_ptr(),
                warn.len(),
                err.as_mut_ptr(),
                err.len(),
            );
            assert!(!s.is_null());
            let w = CStr::from_ptr(warn.as_ptr()).to_str().unwrap();
            assert!(
                w.contains("converter detail"),
                "expected an HVDC converter-detail warning, got {w:?}"
            );
            pio_string_free(s);
        }
    }

    #[test]
    fn snapshot_round_trip_preserves_structure() {
        // to_format("powerio-json") -> parse_str("powerio-json") must reproduce
        // the structured tables. case30 carries loads, shunts, and gen costs,
        // so a dropped field shows up.
        let path = data_path("case30.m");
        let mut err = [0 as c_char; 256];
        let c =
            unsafe { pio_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len()) };
        assert!(!c.is_null());
        unsafe {
            let json = to_format(c, "powerio-json");
            assert!(json.contains("\"buses\""));

            let text = CString::new(json).unwrap();
            let fmt = CString::new("powerio-json").unwrap();
            let back = pio_parse_str(text.as_ptr(), fmt.as_ptr(), err.as_mut_ptr(), err.len());
            assert!(
                !back.is_null(),
                "snapshot parse failed: {}",
                CStr::from_ptr(err.as_ptr()).to_str().unwrap()
            );
            // The snapshot is lossless: no fidelity warnings on the way back.
            assert_eq!(pio_warnings(back, std::ptr::null_mut(), 0), 0);
            // Counts and base survive the round trip.
            assert_eq!(pio_n_buses(back), pio_n_buses(c));
            assert_eq!(pio_n_branches(back), pio_n_branches(c));
            assert_eq!(pio_n_gens(back), pio_n_gens(c));
            assert_eq!(pio_base_mva(back), pio_base_mva(c));
            assert_eq!(pio_ref_bus_index(back), pio_ref_bus_index(c));

            // The bare "json" alias means the same snapshot format.
            let alias = CString::new("json").unwrap();
            let again = pio_parse_str(text.as_ptr(), alias.as_ptr(), err.as_mut_ptr(), err.len());
            assert!(!again.is_null());
            assert_eq!(pio_n_buses(again), pio_n_buses(c));

            pio_network_free(again);
            pio_network_free(back);
            pio_network_free(c);
        }
    }

    #[test]
    fn snapshot_rejects_garbage() {
        let bad = CString::new("{ not json").unwrap();
        let fmt = CString::new("powerio-json").unwrap();
        let mut err = [0 as c_char; 256];
        let h = unsafe { pio_parse_str(bad.as_ptr(), fmt.as_ptr(), err.as_mut_ptr(), err.len()) };
        assert!(h.is_null());
        let msg = unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap();
        assert!(!msg.is_empty(), "expected a JSON parse error message");
    }

    #[test]
    fn error_buffer_truncates_and_nul_terminates() {
        // copy_to_buf must truncate an oversized message to fit and keep the
        // trailing NUL (the one piece of pointer arithmetic in the file).
        let path = CString::new("/no/such/directory/deeply/nested/missing/case.m").unwrap();
        let mut err = [0x7f as c_char; 16]; // prefill nonzero so the NUL is visible
        let c =
            unsafe { pio_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len()) };
        assert!(c.is_null());
        let nul = err
            .iter()
            .position(|&b| b == 0)
            .expect("buffer must be NUL-terminated");
        assert!(nul <= 15);
    }

    #[test]
    fn truncation_lands_on_a_utf8_char_boundary() {
        // "aé€" is 1+2+3 bytes; a 6-byte buffer fits 5 message bytes, which
        // would split '€'. The copy must back up to "aé" instead of emitting a
        // dangling partial codepoint.
        let mut buf = [0x7f as c_char; 6];
        unsafe { copy_to_buf(buf.as_mut_ptr(), buf.len(), "aé€") };
        let s = unsafe { CStr::from_ptr(buf.as_ptr()) }
            .to_str()
            .expect("truncated message must be valid UTF-8");
        assert_eq!(s, "aé");

        // A message that fits is copied whole.
        let mut buf = [0x7f as c_char; 8];
        unsafe { copy_to_buf(buf.as_mut_ptr(), buf.len(), "aé€") };
        let s = unsafe { CStr::from_ptr(buf.as_ptr()) }.to_str().unwrap();
        assert_eq!(s, "aé€");
    }

    #[cfg(feature = "arrow")]
    #[test]
    fn to_arrow_null_out_params_return_error() {
        // A NULL out_array/out_schema must be reported (-1), not dereferenced.
        let c = case9();
        let mut err = [0 as c_char; 256];
        let rc = unsafe {
            pio_to_arrow(
                c,
                PIO_ARROW_TABLE_BUS,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                err.as_mut_ptr(),
                err.len(),
            )
        };
        assert_eq!(rc, -1);
        let msg = unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap();
        assert!(!msg.is_empty(), "expected an error message");
        unsafe { pio_network_free(c) };
    }

    #[cfg(feature = "gridfm")]
    #[test]
    fn read_dir_round_trips_and_enumerates_scenarios() {
        use powerio_matrix::{GridfmOptions, write_gridfm_dataset};
        // Write a one-scenario dataset, then read it back over the C ABI.
        let net = powerio::parse_file(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../tests/data/case14.m"),
            None,
        )
        .unwrap()
        .network;
        let tmp = tempfile::tempdir().unwrap();
        let out = write_gridfm_dataset(&net, 0, tmp.path(), &GridfmOptions::default()).unwrap();
        let dir = CString::new(out.dir.to_str().unwrap()).unwrap();
        let from = CString::new("gridfm").unwrap();

        let mut err = [0 as c_char; 256];
        unsafe {
            let h = pio_read_dir(dir.as_ptr(), from.as_ptr(), 0, err.as_mut_ptr(), err.len());
            assert!(
                !h.is_null(),
                "read failed: {}",
                CStr::from_ptr(err.as_ptr()).to_str().unwrap()
            );
            assert_eq!(pio_n_buses(h), 14);
            // The lossy read's fidelity warnings attach to the handle, like
            // every other constructor's.
            assert!(
                pio_warnings(h, std::ptr::null_mut(), 0) > 0,
                "expected fidelity warnings on the handle"
            );
            pio_network_free(h);

            // Scenario ids: size with a NULL out, then fill. One scenario -> [0].
            let count = pio_scenario_ids(
                dir.as_ptr(),
                from.as_ptr(),
                std::ptr::null_mut(),
                0,
                err.as_mut_ptr(),
                err.len(),
            );
            assert_eq!(count, 1);
            let mut ids = [-1i64; 4];
            let n = pio_scenario_ids(
                dir.as_ptr(),
                from.as_ptr(),
                ids.as_mut_ptr(),
                ids.len(),
                err.as_mut_ptr(),
                err.len(),
            );
            assert_eq!(n, 1);
            assert_eq!(ids[0], 0);

            // An unknown dataset format is a loud error naming the known ones.
            let bad = CString::new("pypsa").unwrap();
            let h = pio_read_dir(dir.as_ptr(), bad.as_ptr(), 0, err.as_mut_ptr(), err.len());
            assert!(h.is_null());
            let msg = CStr::from_ptr(err.as_ptr()).to_str().unwrap();
            assert!(msg.contains("gridfm"), "got: {msg}");

            // A missing dataset directory errors (NULL handle + message), not a panic.
            let missing = CString::new(tmp.path().join("nope").to_str().unwrap()).unwrap();
            let bad = pio_read_dir(
                missing.as_ptr(),
                from.as_ptr(),
                0,
                err.as_mut_ptr(),
                err.len(),
            );
            assert!(bad.is_null());
            assert!(!CStr::from_ptr(err.as_ptr()).to_str().unwrap().is_empty());
        }
    }

    #[test]
    fn write_dir_rejects_text_formats_by_name() {
        let c = case9();
        let to = CString::new("matpower").unwrap();
        let dir = CString::new("/tmp/unused").unwrap();
        let mut err = [0 as c_char; 256];
        unsafe {
            let rc = pio_write_dir(
                c,
                to.as_ptr(),
                dir.as_ptr(),
                std::ptr::null_mut(),
                0,
                err.as_mut_ptr(),
                err.len(),
            );
            assert_eq!(rc, -1);
            let msg = CStr::from_ptr(err.as_ptr()).to_str().unwrap();
            assert!(msg.contains("pypsa"), "got: {msg}");
            pio_network_free(c);
        }
    }

    #[cfg(feature = "dist")]
    mod dist {
        use super::*;
        use std::ffi::CStr;

        fn fourwire() -> std::path::PathBuf {
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../tests/data/dist/micro/fourwire_linecode.dss")
        }

        fn fourwire_cstr() -> CString {
            CString::new(fourwire().to_str().unwrap()).unwrap()
        }

        #[test]
        fn dist_abi_version_is_separate() {
            assert_eq!(pio_abi_version(), PIO_ABI_VERSION);
            assert_eq!(PIO_ABI_VERSION, 4);
            assert_eq!(pio_dist_abi_version(), PIO_DIST_ABI_VERSION);
            assert_eq!(PIO_DIST_ABI_VERSION, 1);
            let feature = CString::new("dist").unwrap();
            assert_eq!(unsafe { pio_has_feature(feature.as_ptr()) }, 1);
        }

        #[test]
        fn parse_file_convert_and_echo() {
            let path = fourwire_cstr();
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let net = unsafe {
                pio_dist_parse_file(path.as_ptr(), std::ptr::null(), err.as_mut_ptr(), err.len())
            };
            assert!(
                !net.is_null(),
                "{}",
                unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap()
            );

            // Cross format write: schema-shaped BMOPF JSON out.
            let to = CString::new("bmopf").unwrap();
            let mut warn = [0 as c_char; 4096];
            let s = unsafe {
                pio_dist_to_format(
                    net,
                    to.as_ptr(),
                    warn.as_mut_ptr(),
                    warn.len(),
                    err.as_mut_ptr(),
                    err.len(),
                )
            };
            assert!(!s.is_null());
            let text = unsafe { CStr::from_ptr(s) }.to_str().unwrap();
            assert!(text.contains("\"bus\""));
            unsafe { pio_string_free(s) };

            // Same format write echoes the retained source byte for byte.
            let to = CString::new("dss").unwrap();
            let s = unsafe {
                pio_dist_to_format(
                    net,
                    to.as_ptr(),
                    warn.as_mut_ptr(),
                    warn.len(),
                    err.as_mut_ptr(),
                    err.len(),
                )
            };
            assert!(!s.is_null());
            let echoed = unsafe { CStr::from_ptr(s) }.to_str().unwrap();
            let source = std::fs::read_to_string(fourwire()).unwrap();
            assert_eq!(echoed, source);
            assert_eq!(
                unsafe { CStr::from_ptr(warn.as_ptr()) }.to_str().unwrap(),
                ""
            );
            unsafe { pio_string_free(s) };

            unsafe { pio_dist_network_free(net) };
        }

        #[test]
        fn convert_str_round_trips_through_pmd() {
            let source = std::fs::read_to_string(fourwire()).unwrap();
            let text = CString::new(source).unwrap();
            let from = CString::new("dss").unwrap();
            let to = CString::new("pmd").unwrap();
            let mut warn = [0 as c_char; 4096];
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let s = unsafe {
                pio_dist_convert_str(
                    text.as_ptr(),
                    from.as_ptr(),
                    to.as_ptr(),
                    warn.as_mut_ptr(),
                    warn.len(),
                    err.as_mut_ptr(),
                    err.len(),
                )
            };
            assert!(
                !s.is_null(),
                "{}",
                unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap()
            );
            let pmd = unsafe { CStr::from_ptr(s) }.to_str().unwrap();
            assert!(pmd.contains("\"data_model\": \"ENGINEERING\""));
            unsafe { pio_string_free(s) };
        }

        #[test]
        fn convert_str_accepts_experimental_julia_order() {
            let source = std::fs::read_to_string(fourwire()).unwrap();
            let text = CString::new(source).unwrap();
            let to = CString::new("pmd").unwrap();
            let from = CString::new("dss").unwrap();
            let mut warn = [0 as c_char; 4096];
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let s = unsafe {
                pio_dist_convert_str(
                    text.as_ptr(),
                    to.as_ptr(),
                    from.as_ptr(),
                    warn.as_mut_ptr(),
                    warn.len(),
                    err.as_mut_ptr(),
                    err.len(),
                )
            };
            assert!(
                !s.is_null(),
                "{}",
                unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap()
            );
            let pmd = unsafe { CStr::from_ptr(s) }.to_str().unwrap();
            assert!(pmd.contains("\"data_model\": \"ENGINEERING\""));
            unsafe { pio_string_free(s) };
        }

        #[test]
        fn warnings_report_count_and_text() {
            // An unknown length unit draws a parse warning; the handle must
            // surface it. Warnings use the size-then-fill idiom of `pio_warnings`.
            let text = CString::new(
                "clear\nnew circuit.w basekv=12.47 bus1=src\nnew line.l1 bus1=src bus2=b2 length=1 units=furlong\n",
            )
            .unwrap();
            let fmt = CString::new("dss").unwrap();
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let net = unsafe {
                pio_dist_parse_str(text.as_ptr(), fmt.as_ptr(), err.as_mut_ptr(), err.len())
            };
            assert!(!net.is_null());
            let mut warn = [0 as c_char; 4096];
            let n = unsafe { pio_dist_warnings(net, warn.as_mut_ptr(), warn.len()) };
            assert!(n > 0, "expected a nonzero warning length");
            let msg = unsafe { CStr::from_ptr(warn.as_ptr()) }.to_str().unwrap();
            assert!(
                msg.lines().any(|w| w.contains("furlong")),
                "expected the units warning, got: {msg}"
            );
            // NULL handle is a 0-length count, not a crash.
            assert_eq!(
                unsafe { pio_dist_warnings(std::ptr::null(), warn.as_mut_ptr(), warn.len()) },
                0
            );
            unsafe { pio_dist_network_free(net) };
        }

        #[test]
        fn convert_file_round_trips_through_bmopf() {
            let path = fourwire_cstr();
            let to = CString::new("bmopf-json").unwrap();
            let mut warn = [0 as c_char; 4096];
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let s = unsafe {
                pio_dist_convert_file(
                    path.as_ptr(),
                    std::ptr::null(),
                    to.as_ptr(),
                    warn.as_mut_ptr(),
                    warn.len(),
                    err.as_mut_ptr(),
                    err.len(),
                )
            };
            assert!(
                !s.is_null(),
                "{}",
                unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap()
            );
            let text = unsafe { CStr::from_ptr(s) }.to_str().unwrap();
            assert!(text.contains("\"bus\""));
            unsafe { pio_string_free(s) };
        }

        #[test]
        fn convert_file_accepts_experimental_julia_order() {
            let path = fourwire_cstr();
            let to = CString::new("bmopf-json").unwrap();
            let mut warn = [0 as c_char; 4096];
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let s = unsafe {
                pio_dist_convert_file(
                    path.as_ptr(),
                    to.as_ptr(),
                    std::ptr::null(),
                    warn.as_mut_ptr(),
                    warn.len(),
                    err.as_mut_ptr(),
                    err.len(),
                )
            };
            assert!(
                !s.is_null(),
                "{}",
                unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap()
            );
            let text = unsafe { CStr::from_ptr(s) }.to_str().unwrap();
            assert!(text.contains("\"bus\""));
            unsafe { pio_string_free(s) };
        }

        #[test]
        fn unknown_format_is_an_error_not_a_crash() {
            let text = CString::new("clear\n").unwrap();
            let fmt = CString::new("matpower").unwrap();
            let mut err = [0 as c_char; PIO_ERRBUF_MIN];
            let net = unsafe {
                pio_dist_parse_str(text.as_ptr(), fmt.as_ptr(), err.as_mut_ptr(), err.len())
            };
            assert!(net.is_null());
            let msg = unsafe { CStr::from_ptr(err.as_ptr()) }.to_str().unwrap();
            assert!(msg.contains("unknown distribution format"));
        }

        #[test]
        fn has_feature_reports_dist() {
            let dist = CString::new("dist").unwrap();
            assert_eq!(unsafe { pio_has_feature(dist.as_ptr()) }, 1);
            let nope = CString::new("nope").unwrap();
            assert_eq!(unsafe { pio_has_feature(nope.as_ptr()) }, 0);
        }
    }
}
