"""Type stubs for the compiled ``powerio._powerio`` extension (PyO3).

Hand-written to match powerio-py/src/lib.rs. Keep in sync when the Rust ABI
changes; this is what makes the ``py.typed`` package statically checkable. The
matrix methods return COO triplets as plain Python lists; the pure-Python
``powerio.BalancedNetwork`` wrapper turns them into scipy/networkx objects.
"""

from typing import Any, Dict, List, Literal, Optional, Tuple

__version__: str
_has_gridfm: bool

class PowerIOError(ValueError):
    """Base error from the powerio parser, converter, or matrix builders.

    Failures mapped from the Rust core carry the diagnostic code string as
    ``code``; it is set at raise time, so it is instance-only.
    """

    code: str

class PowerIOParseError(PowerIOError):
    """A case file is malformed or unparseable."""

class PowerIODataError(PowerIOError):
    """A well-formed case cannot satisfy a requested operation."""

class _BalancedNetwork:
    @property
    def name(self) -> str: ...
    @property
    def base_mva(self) -> float: ...
    @property
    def source_format(
        self,
    ) -> Literal[
        "matpower",
        "powermodels-json",
        "opfdata-json",
        "egret-json",
        "psse",
        "powerworld",
        "pandapower-json",
        "pslf",
        "powerworld-pwb",
        "in-memory",
        "normalized",
        "gridfm",
        "pypsa-csv",
        "goc3-json",
        "surge-json",
    ]: ...
    @property
    def read_warnings(self) -> list[str]: ...
    @property
    def n_buses(self) -> int: ...
    @property
    def n_branches(self) -> int: ...
    @property
    def n_gens(self) -> int: ...
    @property
    def n_loads(self) -> int: ...
    @property
    def n_shunts(self) -> int: ...
    @property
    def is_radial(self) -> bool: ...
    @property
    def n_connected_components(self) -> int: ...
    @property
    def buses(self) -> list[dict]: ...
    @property
    def loads(self) -> list[dict]: ...
    @property
    def shunts(self) -> list[dict]: ...
    @property
    def branches(self) -> list[dict]: ...
    @property
    def switches(self) -> list[dict]: ...
    @property
    def generators(self) -> list[dict]: ...
    def reference_bus_index(self) -> int: ...
    def reference_bus_indices(self) -> list[int]: ...
    def lowered(self) -> _BalancedNetwork: ...
    def connectivity_report(self) -> dict: ...
    def to_matpower(self) -> str: ...
    def to_json(self) -> str: ...
    def to_format(
        self,
        to: str,
        missing_gen_cost: Optional[str] = ...,
        default_gen_cost: Optional[str] = ...,
        gen_cost_csv: Optional[str] = ...,
    ) -> Tuple[str, list[Diagnostic]]: ...
    def to_canonical_format(self, to: str) -> Tuple[str, list[Diagnostic]]: ...
    def write_file(
        self,
        path: str,
        to: str,
        missing_gen_cost: Optional[str] = ...,
        default_gen_cost: Optional[str] = ...,
        gen_cost_csv: Optional[str] = ...,
    ) -> list[str]: ...
    def to_normalized(self) -> _BalancedNetwork: ...
    def geo_layer_json(self) -> str: ...
    def apply_geo_layer(
        self, text: str, name_hint: Optional[str] = ...
    ) -> Tuple["_BalancedNetwork", dict[str, Any]]: ...
    def to_normalized_with_options(
        self,
        *,
        clamp_angle_bounds: bool = ...,
        angle_bound_pad: Optional[float] = ...,
    ) -> _BalancedNetwork: ...
    def write_pypsa_csv_folder(self, out_dir: str) -> dict: ...
    # Matrix builders return COO triplets `(data, row, col, (nrows, ncols))` as
    # plain Python lists, except `incidence`/`ybus_parts` which nest them.
    def bprime(self, scheme: Optional[str] = ...) -> Any: ...
    def dc_data(self, formula: str = ...) -> Dict[str, Any]: ...
    def bdoubleprime(self, scheme: Optional[str] = ...) -> Any: ...
    def lacpf(self, *, include_taps: bool = ..., include_shifts: bool = ...) -> Any: ...
    def adjacency(self) -> Any: ...
    def ybus_parts(
        self, *, include_taps: bool = ..., include_shifts: bool = ...
    ) -> Any: ...
    def ptdf(self, convention: Optional[str] = ..., solver: Optional[str] = ...) -> Any: ...
    def lodf(self, convention: Optional[str] = ..., solver: Optional[str] = ...) -> Any: ...
    def weighted_laplacian(self, convention: Optional[str] = ...) -> Any: ...
    def incidence(self, convention: Optional[str] = ...) -> Any: ...
    def write_dcopf_bundle(
        self,
        out_dir: str,
        convention: Optional[str] = ...,
        units: Optional[str] = ...,
        missing_gen_cost: Optional[str] = ...,
        default_gen_cost: Optional[str] = ...,
        gen_cost_csv: Optional[str] = ...,
    ) -> dict: ...
    # Only present when the extension was compiled with the `gridfm` cargo
    # feature (the released wheel is); without it, access raises AttributeError.
    def write_gridfm(
        self,
        out_dir: str,
        *,
        scenario: int = ...,
        include_y_bus: bool = ...,
        include_taps: bool = ...,
        include_shifts: bool = ...,
        missing_gen_cost: Optional[str] = ...,
        default_gen_cost: Optional[str] = ...,
        gen_cost_csv: Optional[str] = ...,
    ) -> dict: ...
    def __repr__(self) -> str: ...

class _MulticonductorNetwork:
    def name(self) -> Optional[str]: ...
    def source_format(self) -> Optional[str]: ...
    def warnings(self) -> list[str]: ...
    def n_buses(self) -> int: ...
    def n_lines(self) -> int: ...
    def n_transformers(self) -> int: ...
    def n_loads(self) -> int: ...
    def n_generators(self) -> int: ...
    def n_sources(self) -> int: ...
    def graph_json(self) -> str: ...
    def to_format(self, to: str) -> Tuple[str, list[Diagnostic]]: ...
    def to_canonical_format(self, to: str) -> Tuple[str, list[Diagnostic]]: ...
    def write_file(self, path: str, to: str) -> list[str]: ...
    def geo_layer_json(self) -> str: ...
    def apply_geo_layer(
        self, text: str, name_hint: Optional[str] = ...
    ) -> Tuple["_MulticonductorNetwork", dict[str, Any]]: ...
    def __repr__(self) -> str: ...

def parse_display_file(path: str, from_: Optional[str] = ...) -> Tuple[str, dict[str, Any]]: ...
def parse_display_bytes(data: bytes, from_: str) -> Tuple[str, dict[str, Any]]: ...
def classify_json_text(text: str) -> Tuple[str, Optional[str], Optional[str]]: ...
def json_classes() -> List[str]: ...
def parse_geo(text: str, name_hint: Optional[str] = ...) -> dict[str, Any]: ...
def from_json(text: str) -> _BalancedNetwork: ...
def convert_file(
    path: str,
    to: str,
    from_: Optional[str] = ...,
    missing_gen_cost: Optional[str] = ...,
    default_gen_cost: Optional[str] = ...,
    gen_cost_csv: Optional[str] = ...,
    out: Optional[str] = ...,
) -> Tuple[str, list[Diagnostic]]: ...
def convert_str(
    text: str,
    to: str,
    from_: Optional[str] = ...,
    missing_gen_cost: Optional[str] = ...,
    default_gen_cost: Optional[str] = ...,
    gen_cost_csv: Optional[str] = ...,
) -> Tuple[str, list[Diagnostic]]: ...
def dist_parse_file(
    path: str, from_: Optional[str] = ..., include_root: Optional[str] = ...
) -> _MulticonductorNetwork: ...
def dist_parse_str(text: str, from_: str) -> _MulticonductorNetwork: ...
def dist_convert_file(
    path: str, to: str, from_: Optional[str] = ...
) -> Tuple[str, list[Diagnostic]]: ...
def dist_convert_str(text: str, to: str, from_: str) -> Tuple[str, list[Diagnostic]]: ...
def versions_json() -> str: ...

class SourceSpan:
    """One source byte range a diagnostic points at (frozen)."""

    @property
    def source(self) -> str: ...
    @property
    def byte_start(self) -> int: ...
    @property
    def byte_end(self) -> int: ...
    def __repr__(self) -> str: ...

class Diagnostic:
    """One coded, user facing finding from a parse, read, transform, or
    write pass (frozen)."""

    @property
    def code(self) -> str: ...
    @property
    def severity(self) -> Literal["error", "warning", "remark", "note"]: ...
    @property
    def message(self) -> str: ...
    @property
    def id(self) -> Optional[str]: ...
    @property
    def target(self) -> Optional[str]: ...
    @property
    def suggested_action(self) -> Optional[str]: ...
    @property
    def related(self) -> list[str]: ...
    @property
    def spans(self) -> list[SourceSpan]: ...
    @property
    def details(self) -> Optional[dict[str, Any]]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _PioModule:
    @staticmethod
    def from_json(text: str) -> "_PioModule": ...
    @staticmethod
    def from_file(
        path: str, from_: Optional[str] = ..., include_root: Optional[str] = ...
    ) -> "_PioModule": ...
    @staticmethod
    def from_str(text: str, from_: Optional[str] = ...) -> "_PioModule": ...
    @staticmethod
    def from_bytes(data: bytes, from_: Optional[str] = ...) -> "_PioModule": ...
    def to_json(self) -> str: ...
    def kind(self) -> str: ...
    def inspect_json(self) -> str: ...
    def diagnostics_json(self) -> str: ...
    def diagnostics(self) -> list[Diagnostic]: ...
    def state_inventory_json(self) -> str: ...
    def select_json(
        self, time_position: Optional[int] = ..., scenario: Optional[str] = ...
    ) -> str: ...
    def export_selected(
        self, time_position: Optional[int] = ..., scenario: Optional[str] = ...
    ) -> "_PioModule": ...
    def lowering_readiness_json(self, base_mva: float = ...) -> str: ...
    def lower_to_balanced(self, base_mva: float = ...) -> "_PioModule": ...
    def as_balanced_network(self) -> _BalancedNetwork: ...
    def as_multiconductor_network(self) -> _MulticonductorNetwork: ...
    def __repr__(self) -> str: ...

# Only present when the extension was compiled with the `gridfm` cargo feature
# (the released wheel is); without it, access raises AttributeError.
def write_gridfm_batch(
    cases: list[_BalancedNetwork],
    out_dir: str,
    *,
    base_scenario: int = ...,
    include_y_bus: bool = ...,
    include_taps: bool = ...,
    include_shifts: bool = ...,
    missing_gen_cost: Optional[str] = ...,
    default_gen_cost: Optional[str] = ...,
    gen_cost_csv: Optional[str] = ...,
) -> dict: ...
def read_gridfm(dir: str, scenario: int = ...) -> Tuple[_BalancedNetwork, int, list[str]]: ...
def read_gridfm_scenarios(dir: str) -> list[Tuple[_BalancedNetwork, int, list[str]]]: ...
