"""Type stubs for the compiled ``powerio._powerio`` extension (PyO3).

Hand-written to match powerio-py/src/lib.rs. Keep in sync when the Rust ABI
changes; this is what makes the ``py.typed`` package statically checkable. The
matrix methods return COO triplets as plain Python lists; the pure-Python
``powerio.Case`` wrapper turns them into scipy/networkx objects.
"""

from typing import Any, Optional, Tuple

__version__: str

class PowerIOError(Exception):
    """Raised by the powerio parser, converter, or matrix builders."""

class PyCase:
    @property
    def name(self) -> str: ...
    @property
    def base_mva(self) -> float: ...
    @property
    def source_format(self) -> str: ...
    @property
    def n(self) -> int: ...
    @property
    def n_branches(self) -> int: ...
    @property
    def n_gens(self) -> int: ...
    @property
    def n_loads(self) -> int: ...
    @property
    def n_shunts(self) -> int: ...
    @property
    def is_radial(self) -> bool: ...
    @property
    def n_connected_components(self) -> int: ...
    @property
    def buses(self) -> list[dict]: ...
    @property
    def loads(self) -> list[dict]: ...
    @property
    def shunts(self) -> list[dict]: ...
    @property
    def branches(self) -> list[dict]: ...
    @property
    def gens(self) -> list[dict]: ...
    def reference_bus_index(self) -> int: ...
    def connectivity_report(self) -> dict: ...
    def write(self) -> str: ...
    # Matrix builders return COO triplets `(data, row, col, (nrows, ncols))` as
    # plain Python lists, except `incidence`/`ybus_parts` which nest them.
    def bprime(self, scheme: Optional[str] = ...) -> Any: ...
    def bdoubleprime(self, scheme: Optional[str] = ...) -> Any: ...
    def lacpf(self, include_taps: bool = ..., include_shifts: bool = ...) -> Any: ...
    def adjacency(self) -> Any: ...
    def ybus_parts(
        self, include_taps: bool = ..., include_shifts: bool = ...
    ) -> Any: ...
    def ptdf(self, convention: Optional[str] = ...) -> Any: ...
    def lodf(self, convention: Optional[str] = ...) -> Any: ...
    def weighted_laplacian(self, convention: Optional[str] = ...) -> Any: ...
    def incidence(self, convention: Optional[str] = ...) -> Any: ...
    def write_dcopf_bundle(
        self, out_dir: str, convention: Optional[str] = ..., units: Optional[str] = ...
    ) -> dict: ...
    def __repr__(self) -> str: ...

def parse(path: str) -> PyCase: ...
def parse_str(text: str, format: Optional[str] = ...) -> PyCase: ...
def parse_matpower(path: str) -> PyCase: ...
def parse_matpower_string(content: str, name: Optional[str] = ...) -> PyCase: ...
def write(case: PyCase) -> str: ...
def convert(path: str, to: str, from_: Optional[str] = ...) -> Tuple[str, list[str]]: ...
