"""Type stubs for the compiled ``powerio._powerio`` extension (PyO3).

Hand-written to match powerio-py/src/lib.rs. Keep in sync when the Rust ABI
changes; this is what makes the ``py.typed`` package statically checkable. The
matrix methods return COO triplets as plain Python lists; the pure-Python
``powerio.BalancedNetwork`` wrapper turns them into scipy/networkx objects.
"""

from typing import Any, Dict, List, Literal, Optional, Tuple, final, overload

__version__: str
_has_gridfm: bool
__all__ = [
    "ActivePower",
    "ApparentPower",
    "CalculationUpdate",
    "ComponentId",
    "Diagnostic",
    "NetworkUpdate",
    "OperatingPointUpdate",
    "PowerIODataError",
    "PowerIOError",
    "PowerIOParseError",
    "ReactivePower",
    "Residuals",
    "ScucActiveReserveZone",
    "ScucBranchSwitchingCost",
    "ScucContingency",
    "ScucDevice",
    "ScucDeviceOutputs",
    "ScucDevicePeriod",
    "ScucEnergyCostBlock",
    "ScucEnergyRequirement",
    "ScucInitialCommitment",
    "ScucInputs",
    "ScucNetworkOutputs",
    "ScucRampLimits",
    "ScucReactiveCapability",
    "ScucReactiveReserveZone",
    "ScucReserveCosts",
    "ScucReserveLimits",
    "ScucShunt",
    "ScucStartupCostAdjustment",
    "ScucStartupLimit",
    "ScucTransformerControl",
    "ScucViolationCosts",
    "SourceSpan",
    "UpdateChange",
    "UpdateReport",
    "_BalancedNetwork",
    "_MulticonductorNetwork",
    "_PioModule",
    "__version__",
    "_has_gridfm",
    "classify_json_text",
    "json_classes",
    "parse_display",
    "parse_geo",
    "resolve_format",
    "versions_json",
]

class PowerIOError(ValueError):
    """Base error from the powerio parser, emitter, or matrix calculations.

    Failures mapped from the Rust core carry the diagnostic code string as
    ``code``; it is set at raise time, so it is instance-only.
    """

    code: str

class PowerIOParseError(PowerIOError):
    """A case file is malformed or unparseable."""

class PowerIODataError(PowerIOError):
    """A well-formed case cannot satisfy a requested operation.

    A refused pass (e.g. ``_PioModule.lower_to_balanced``) additionally sets
    ``diagnostics``: the pass's structured findings, each a dict with
    ``code``, ``severity``, ``message``, and ``target``. Absent on a
    ``PowerIODataError`` raised elsewhere.
    """

    diagnostics: List[Dict[str, Any]]

class _BalancedNetwork:
    @property
    def name(self) -> str: ...
    @property
    def base_mva(self) -> float: ...
    @property
    def base_frequency(self) -> float: ...
    @property
    def source_format(
        self,
    ) -> Literal[
        "matpower",
        "powermodels-json",
        "opfdata-json",
        "egret-json",
        "psse",
        "psse-rawx",
        "powerworld",
        "pandapower-json",
        "pslf",
        "powerworld-pwb",
        "in-memory",
        "normalized",
        "gridfm",
        "pypsa-csv",
        "goc3-json",
        "surge-json",
        "xiidm",
        "jiidm",
        "cgmes",
        "ucte",
        "ieee-cdf",
    ]: ...
    @property
    def n_buses(self) -> int: ...
    @property
    def n_branches(self) -> int: ...
    @property
    def n_generators(self) -> int: ...
    @property
    def n_loads(self) -> int: ...
    @property
    def n_shunts(self) -> int: ...
    @property
    def n_static_var_compensators(self) -> int: ...
    @property
    def n_switches(self) -> int: ...
    @property
    def n_storage(self) -> int: ...
    @property
    def n_hvdc(self) -> int: ...
    @property
    def n_transformers_3w(self) -> int: ...
    @property
    def n_areas(self) -> int: ...
    @property
    def detailed_connectivity(self) -> Optional[Dict[str, Any]]: ...
    @property
    def is_radial(self) -> bool: ...
    @property
    def n_connected_components(self) -> int: ...
    @property
    def n_islands(self) -> int: ...
    @property
    def buses(self) -> list[dict]: ...
    @property
    def loads(self) -> list[dict]: ...
    @property
    def shunts(self) -> list[dict]: ...
    @property
    def static_var_compensators(self) -> list[dict]: ...
    @property
    def branches(self) -> list[dict]: ...
    @property
    def switches(self) -> list[dict]: ...
    @property
    def generators(self) -> list[dict]: ...
    @property
    def storage(self) -> list[dict]: ...
    @property
    def hvdc(self) -> list[dict]: ...
    @property
    def transformers_3w(self) -> list[dict]: ...
    @property
    def areas(self) -> list[dict]: ...
    def reference_bus_index(self) -> int: ...
    def reference_bus_indices(self) -> list[int]: ...
    def lowered(self) -> _BalancedNetwork: ...
    def calc_connectivity_report(self) -> dict: ...
    def to_normalized(self) -> _BalancedNetwork: ...
    def to_geo_layer_json(self) -> str: ...
    def apply_geo_layer(
        self, text: str, name_hint: Optional[str] = ...
    ) -> Tuple["_BalancedNetwork", dict[str, Any]]: ...
    def to_normalized_with_options(
        self,
        *,
        clamp_angle_bounds: bool = ...,
        angle_bound_pad: Optional[float] = ...,
    ) -> _BalancedNetwork: ...
    # Matrix builders return COO triplets `(data, row, col, (nrows, ncols))` as
    # plain Python lists, except `incidence`/`ybus_parts` which nest them.
    def bprime(
        self, scheme: Optional[str] = ..., *, skip_zero_impedance: bool = ...
    ) -> Any: ...
    def calc_incidence_matrix(self, formula: str = ...) -> Any: ...
    def calc_branch_susceptances(self, formula: str = ...) -> List[float]: ...
    def calc_branch_flow_matrix(self, formula: str = ...) -> Any: ...
    def calc_bus_susceptance_matrix(self, formula: str = ...) -> Any: ...
    def calc_branch_phase_shift_injection(self, formula: str = ...) -> List[float]: ...
    def calc_bus_phase_shift_injection(self, formula: str = ...) -> List[float]: ...
    def calc_branch_flow_dc(
        self, voltage_angles: List[float], formula: str = ...
    ) -> List[float]: ...
    def calc_bus_injection_dc(
        self, voltage_angles: List[float], formula: str = ...
    ) -> List[float]: ...
    def bdoubleprime(
        self, scheme: Optional[str] = ..., *, skip_zero_impedance: bool = ...
    ) -> Any: ...
    def lacpf(
        self,
        *,
        include_taps: bool = ...,
        include_shifts: bool = ...,
        skip_zero_impedance: bool = ...,
    ) -> Any: ...
    def adjacency(self) -> Any: ...
    def ybus_parts(
        self,
        *,
        include_taps: bool = ...,
        include_shifts: bool = ...,
        skip_zero_impedance: bool = ...,
    ) -> Any: ...
    def ptdf(
        self, formula: Optional[str] = ..., solver: Optional[str] = ...
    ) -> Any: ...
    def lodf(
        self, formula: Optional[str] = ..., solver: Optional[str] = ...
    ) -> Any: ...
    def weighted_laplacian(self, formula: Optional[str] = ...) -> Any: ...
    def __repr__(self) -> str: ...

class _MulticonductorNetwork:
    def name(self) -> Optional[str]: ...
    def source_format(self) -> Optional[str]: ...
    def base_frequency(self) -> float: ...
    def n_buses(self) -> int: ...
    def n_lines(self) -> int: ...
    def n_line_codes(self) -> int: ...
    def n_switches(self) -> int: ...
    def n_transformers(self) -> int: ...
    def n_loads(self) -> int: ...
    def n_generators(self) -> int: ...
    def n_ibrs(self) -> int: ...
    def n_control_profiles(self) -> int: ...
    def n_shunts(self) -> int: ...
    def n_capacitors(self) -> int: ...
    def n_voltage_sources(self) -> int: ...
    def n_untyped_objects(self) -> int: ...
    def buses(self) -> list[dict[str, Any]]: ...
    def line_codes(self) -> list[dict[str, Any]]: ...
    def lines(self) -> list[dict[str, Any]]: ...
    def switches(self) -> list[dict[str, Any]]: ...
    def transformers(self) -> list[dict[str, Any]]: ...
    def loads(self) -> list[dict[str, Any]]: ...
    def generators(self) -> list[dict[str, Any]]: ...
    def ibrs(self) -> list[dict[str, Any]]: ...
    def control_profiles(self) -> list[dict[str, Any]]: ...
    def shunts(self) -> list[dict[str, Any]]: ...
    def capacitors(self) -> list[dict[str, Any]]: ...
    def voltage_sources(self) -> list[dict[str, Any]]: ...
    def untyped_objects(self) -> list[dict[str, Any]]: ...
    def graph_json(self) -> str: ...
    def to_geo_layer_json(self) -> str: ...
    def apply_geo_layer(
        self, text: str, name_hint: Optional[str] = ...
    ) -> Tuple["_MulticonductorNetwork", dict[str, Any]]: ...
    def __repr__(self) -> str: ...

def parse_display(
    path: str, from_: Optional[str] = ...
) -> Tuple[str, dict[str, Any]]: ...
def classify_json_text(text: str) -> Tuple[str, Optional[str], Optional[str]]: ...
def json_classes() -> List[str]: ...
def resolve_format(
    name: str,
) -> Optional[Tuple[str, Optional[str], bool, bool]]: ...
def parse_geo(text: str, name_hint: Optional[str] = ...) -> dict[str, Any]: ...
def versions_json() -> str: ...

class SourceSpan:
    """One source byte range a diagnostic points at (frozen)."""

    @property
    def source(self) -> str: ...
    @property
    def byte_start(self) -> int: ...
    @property
    def byte_end(self) -> int: ...
    def __repr__(self) -> str: ...

class Diagnostic:
    """One coded, user facing finding from a parse, read, transform, or
    write pass (frozen)."""

    @property
    def code(self) -> str: ...
    @property
    def severity(self) -> Literal["error", "warning", "remark", "note"]: ...
    @property
    def message(self) -> str: ...
    @property
    def id(self) -> Optional[str]: ...
    @property
    def target(self) -> Optional[str]: ...
    @property
    def suggested_action(self) -> Optional[str]: ...
    @property
    def related(self) -> list[str]: ...
    @property
    def spans(self) -> list[SourceSpan]: ...
    @property
    def details(self) -> Optional[dict[str, Any]]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

@final
class ComponentId:
    def __new__(cls, component_type: str, local_id: str) -> ComponentId: ...
    @property
    def component_type(self) -> str: ...
    @property
    def local_id(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScucStartupCostAdjustment:
    @property
    def cost(self) -> float: ...
    @property
    def maximum_down_time(self) -> float: ...

@final
class ScucStartupLimit:
    @property
    def start_time(self) -> float: ...
    @property
    def end_time(self) -> float: ...
    @property
    def maximum_startups(self) -> int: ...

@final
class ScucEnergyRequirement:
    @property
    def start_time(self) -> float: ...
    @property
    def end_time(self) -> float: ...
    @property
    def energy(self) -> float: ...

@final
class ScucInitialCommitment:
    @property
    def accumulated_up_time(self) -> float: ...
    @property
    def accumulated_down_time(self) -> float: ...

@final
class ScucRampLimits:
    @property
    def up(self) -> float: ...
    @property
    def down(self) -> float: ...
    @property
    def startup(self) -> float: ...
    @property
    def shutdown(self) -> float: ...

@final
class ScucReserveLimits:
    @property
    def regulation_up(self) -> float: ...
    @property
    def regulation_down(self) -> float: ...
    @property
    def synchronized(self) -> float: ...
    @property
    def nonsynchronized(self) -> float: ...
    @property
    def ramping_up_online(self) -> float: ...
    @property
    def ramping_down_online(self) -> float: ...
    @property
    def ramping_up_offline(self) -> float: ...
    @property
    def ramping_down_offline(self) -> float: ...

@final
class ScucReactiveCapability:
    @property
    def kind(self) -> Literal["none", "linear", "bounded"]: ...
    @property
    def reactive_power_at_zero_active_power(self) -> Optional[float]: ...
    @property
    def reactive_power_at_zero_active_power_min(self) -> Optional[float]: ...
    @property
    def reactive_power_at_zero_active_power_max(self) -> Optional[float]: ...
    @property
    def slope(self) -> Optional[float]: ...
    @property
    def slope_min(self) -> Optional[float]: ...
    @property
    def slope_max(self) -> Optional[float]: ...

@final
class ScucEnergyCostBlock:
    @property
    def marginal_cost(self) -> float: ...
    @property
    def block_size(self) -> float: ...

@final
class ScucReserveCosts:
    @property
    def regulation_up(self) -> float: ...
    @property
    def regulation_down(self) -> float: ...
    @property
    def synchronized(self) -> float: ...
    @property
    def nonsynchronized(self) -> float: ...
    @property
    def ramping_up_online(self) -> float: ...
    @property
    def ramping_down_online(self) -> float: ...
    @property
    def ramping_up_offline(self) -> float: ...
    @property
    def ramping_down_offline(self) -> float: ...
    @property
    def reactive_up(self) -> float: ...
    @property
    def reactive_down(self) -> float: ...

@final
class ScucDevicePeriod:
    @property
    def on_status_min(self) -> bool: ...
    @property
    def on_status_max(self) -> bool: ...
    @property
    def active_power_min(self) -> float: ...
    @property
    def active_power_max(self) -> float: ...
    @property
    def reactive_power_min(self) -> float: ...
    @property
    def reactive_power_max(self) -> float: ...
    @property
    def energy_cost_blocks(self) -> Tuple[ScucEnergyCostBlock, ...]: ...
    @property
    def reserve_costs(self) -> ScucReserveCosts: ...

@final
class ScucDevice:
    @property
    def id(self) -> ComponentId: ...
    @property
    def kind(self) -> Literal["producer", "consumer"]: ...
    @property
    def on_cost(self) -> float: ...
    @property
    def startup_cost(self) -> float: ...
    @property
    def startup_cost_adjustments(
        self,
    ) -> Tuple[ScucStartupCostAdjustment, ...]: ...
    @property
    def shutdown_cost(self) -> float: ...
    @property
    def startup_limits(self) -> Tuple[ScucStartupLimit, ...]: ...
    @property
    def energy_upper_bounds(self) -> Tuple[ScucEnergyRequirement, ...]: ...
    @property
    def energy_lower_bounds(self) -> Tuple[ScucEnergyRequirement, ...]: ...
    @property
    def minimum_up_time(self) -> float: ...
    @property
    def minimum_down_time(self) -> float: ...
    @property
    def ramp_limits(self) -> ScucRampLimits: ...
    @property
    def reserve_limits(self) -> ScucReserveLimits: ...
    @property
    def initial_on_status(self) -> bool: ...
    @property
    def initial_commitment(self) -> ScucInitialCommitment: ...
    @property
    def reactive_capability(self) -> ScucReactiveCapability: ...
    @property
    def periods(self) -> Tuple[ScucDevicePeriod, ...]: ...

@final
class ScucShunt:
    @property
    def id(self) -> ComponentId: ...
    @property
    def conductance_per_step(self) -> float: ...
    @property
    def susceptance_per_step(self) -> float: ...
    @property
    def step_min(self) -> int: ...
    @property
    def step_max(self) -> int: ...
    @property
    def initial_step(self) -> int: ...

@final
class ScucBranchSwitchingCost:
    @property
    def id(self) -> ComponentId: ...
    @property
    def connection_cost(self) -> float: ...
    @property
    def disconnection_cost(self) -> float: ...

@final
class ScucTransformerControl:
    @property
    def id(self) -> ComponentId: ...
    @property
    def tap_ratio_min(self) -> float: ...
    @property
    def tap_ratio_max(self) -> float: ...
    @property
    def phase_shift_min(self) -> float: ...
    @property
    def phase_shift_max(self) -> float: ...

@final
class ScucActiveReserveZone:
    @property
    def id(self) -> ComponentId: ...
    @property
    def buses(self) -> Tuple[ComponentId, ...]: ...
    @property
    def regulation_up_requirement_fraction(self) -> float: ...
    @property
    def regulation_down_requirement_fraction(self) -> float: ...
    @property
    def synchronized_requirement_fraction(self) -> float: ...
    @property
    def nonsynchronized_requirement_fraction(self) -> float: ...
    @property
    def ramping_up_requirement(self) -> Tuple[float, ...]: ...
    @property
    def ramping_down_requirement(self) -> Tuple[float, ...]: ...
    @property
    def regulation_up_violation_cost(self) -> float: ...
    @property
    def regulation_down_violation_cost(self) -> float: ...
    @property
    def synchronized_violation_cost(self) -> float: ...
    @property
    def nonsynchronized_violation_cost(self) -> float: ...
    @property
    def ramping_up_violation_cost(self) -> float: ...
    @property
    def ramping_down_violation_cost(self) -> float: ...

@final
class ScucReactiveReserveZone:
    @property
    def id(self) -> ComponentId: ...
    @property
    def buses(self) -> Tuple[ComponentId, ...]: ...
    @property
    def reactive_up_requirement(self) -> Tuple[float, ...]: ...
    @property
    def reactive_down_requirement(self) -> Tuple[float, ...]: ...
    @property
    def reactive_up_violation_cost(self) -> float: ...
    @property
    def reactive_down_violation_cost(self) -> float: ...

@final
class ScucContingency:
    @property
    def id(self) -> ComponentId: ...
    @property
    def components(self) -> Tuple[ComponentId, ...]: ...

@final
class ScucViolationCosts:
    @property
    def active_power_balance(self) -> float: ...
    @property
    def reactive_power_balance(self) -> float: ...
    @property
    def branch_thermal_limit(self) -> float: ...
    @property
    def energy_requirement(self) -> float: ...

@final
class ScucInputs:
    @property
    def interval_durations(self) -> Tuple[float, ...]: ...
    @property
    def devices(self) -> Tuple[ScucDevice, ...]: ...
    @property
    def shunts(self) -> Tuple[ScucShunt, ...]: ...
    @property
    def branch_switching_costs(self) -> Tuple[ScucBranchSwitchingCost, ...]: ...
    @property
    def transformer_controls(self) -> Tuple[ScucTransformerControl, ...]: ...
    @property
    def active_reserve_zones(self) -> Tuple[ScucActiveReserveZone, ...]: ...
    @property
    def reactive_reserve_zones(self) -> Tuple[ScucReactiveReserveZone, ...]: ...
    @property
    def contingencies(self) -> Tuple[ScucContingency, ...]: ...
    @property
    def violation_costs(self) -> ScucViolationCosts: ...

@final
class Residuals:
    @property
    def max_active_power_mismatch(self) -> Optional[float]: ...
    @property
    def max_reactive_power_mismatch(self) -> Optional[float]: ...

@final
class ScucNetworkOutputs:
    @property
    def bus_vm(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def bus_va(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def shunt_step(self) -> Tuple[Tuple[int, ...], ...]: ...
    @property
    def ac_line_on_status(self) -> Tuple[Tuple[bool, ...], ...]: ...
    @property
    def transformer_tm(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def transformer_ta(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def transformer_on_status(self) -> Tuple[Tuple[bool, ...], ...]: ...
    @property
    def dc_line_pdc_fr(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def dc_line_qdc_fr(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def dc_line_qdc_to(self) -> Tuple[Tuple[float, ...], ...]: ...

@final
class ScucDeviceOutputs:
    @property
    def on_status(self) -> Tuple[Tuple[bool, ...], ...]: ...
    @property
    def startup_status(self) -> Tuple[Tuple[bool, ...], ...]: ...
    @property
    def shutdown_status(self) -> Tuple[Tuple[bool, ...], ...]: ...
    @property
    def p_on(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def q(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_reg_res_up(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_reg_res_down(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_syn_res(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_nsyn_res(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_ramp_res_up_online(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_ramp_res_up_offline(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_ramp_res_down_online(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def p_ramp_res_down_offline(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def q_res_up(self) -> Tuple[Tuple[float, ...], ...]: ...
    @property
    def q_res_down(self) -> Tuple[Tuple[float, ...], ...]: ...

@final
class ActivePower:
    @staticmethod
    def watts(value: float) -> ActivePower: ...
    @staticmethod
    def megawatts(value: float) -> ActivePower: ...
    @property
    def value(self) -> float: ...
    @property
    def unit(self) -> Literal["watts", "megawatts"]: ...

@final
class ReactivePower:
    @staticmethod
    def vars(value: float) -> ReactivePower: ...
    @staticmethod
    def megavars(value: float) -> ReactivePower: ...
    @property
    def value(self) -> float: ...
    @property
    def unit(self) -> Literal["vars", "megavars"]: ...

@final
class ApparentPower:
    @staticmethod
    def volt_amperes(value: float) -> ApparentPower: ...
    @staticmethod
    def megavolt_amperes(value: float) -> ApparentPower: ...
    @property
    def value(self) -> float: ...
    @property
    def unit(self) -> Literal["volt_amperes", "megavolt_amperes"]: ...

@final
class OperatingPointUpdate:
    @staticmethod
    def set_load_active_power(
        load: ComponentId, p: ActivePower, *, terminal: Optional[str] = ...
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_load_reactive_power(
        load: ComponentId, q: ReactivePower, *, terminal: Optional[str] = ...
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_generator_active_power(
        generator: ComponentId, p: ActivePower, *, terminal: Optional[str] = ...
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_generator_reactive_power(
        generator: ComponentId, q: ReactivePower, *, terminal: Optional[str] = ...
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_generator_voltage_magnitude(
        generator: ComponentId, vm_pu: float
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_generator_in_service(
        generator: ComponentId, in_service: bool
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_branch_in_service(
        branch: ComponentId, in_service: bool
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_transformer_tap_ratio(
        transformer: ComponentId, tap_ratio: float
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_transformer_phase_shift(
        transformer: ComponentId, shift_degrees: float
    ) -> OperatingPointUpdate: ...
    @staticmethod
    def set_switch_closed(
        switch: ComponentId, closed: bool
    ) -> OperatingPointUpdate: ...
    @property
    def field(self) -> str: ...

@final
class NetworkUpdate:
    @staticmethod
    def set_branch_thermal_rating(
        branch: ComponentId,
        rating: ApparentPower,
        *,
        terminal: Optional[str] = ...,
    ) -> NetworkUpdate: ...
    @property
    def field(self) -> Literal["branch_thermal_rating"]: ...

@final
class CalculationUpdate:
    @overload
    def __new__(cls, update: OperatingPointUpdate) -> CalculationUpdate: ...
    @overload
    def __new__(cls, update: NetworkUpdate) -> CalculationUpdate: ...
    @property
    def data_role(self) -> Literal["operating_point", "network"]: ...

@final
class UpdateChange:
    @property
    def component_id(self) -> ComponentId: ...
    @property
    def field(self) -> str: ...
    @property
    def terminal(self) -> Optional[str]: ...

@final
class UpdateReport:
    @property
    def changes(self) -> List[UpdateChange]: ...
    @property
    def connectivity_changed(self) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

class _PioModule:
    @staticmethod
    def from_balanced_network(network: _BalancedNetwork) -> "_PioModule": ...
    @staticmethod
    def from_multiconductor_network(
        network: _MulticonductorNetwork,
    ) -> "_PioModule": ...
    @staticmethod
    def _parse_path(path: str, format: Optional[str] = ...) -> "_PioModule": ...
    @staticmethod
    def _parse_memory(
        data: bytes, name: str, format: Optional[str] = ...
    ) -> "_PioModule": ...
    @staticmethod
    def _deserialize_path(path: str) -> "_PioModule": ...
    @staticmethod
    def _deserialize_memory(data: bytes) -> "_PioModule": ...
    def _emit_memory(self, format: str) -> dict[str, Any]: ...
    def _emit_path(self, format: str, path: str) -> dict[str, Any]: ...
    def _serialize_memory(self) -> dict[str, Any]: ...
    def _serialize_path(self, path: str) -> dict[str, Any]: ...
    def _to_dc_pf_instance(self) -> "_PioModule": ...
    def _to_ac_pf_instance(self) -> "_PioModule": ...
    def _to_dc_opf_instance(self) -> "_PioModule": ...
    def _to_ac_opf_instance(self) -> "_PioModule": ...
    def _to_mc_ac_pf_instance(self) -> "_PioModule": ...
    def _to_mc_ac_opf_instance(self) -> "_PioModule": ...
    def _balanced_calculation_network(self) -> _BalancedNetwork: ...
    def _multiconductor_calculation_network(self) -> _MulticonductorNetwork: ...
    def _calculation_solution_instance(self) -> "_PioModule": ...
    def _ac_scuc_inputs(self) -> ScucInputs: ...
    def _ac_scuc_solution_termination(
        self,
    ) -> Literal[
        "converged",
        "iteration_limit",
        "infeasible",
        "unbounded",
        "failed",
        "not_reported",
    ]: ...
    def _ac_scuc_solution_residuals(self) -> Residuals: ...
    def _ac_scuc_solution_producer(self) -> Optional[str]: ...
    def _ac_scuc_solution_network_outputs(self) -> ScucNetworkOutputs: ...
    def _ac_scuc_solution_device_outputs(self) -> ScucDeviceOutputs: ...
    def _ac_scuc_solution_objective(self) -> Optional[float]: ...
    @property
    def _type_name(self) -> str: ...
    @property
    def diagnostics(self) -> List[Diagnostic]: ...
    def _apply_updates(self, updates: Any) -> UpdateReport: ...
    def _apply_bus_load_active_power(
        self,
        bus_id: int,
        total: ActivePower,
        *,
        allocation: str = ...,
    ) -> UpdateReport: ...
    def _apply_collection_updates(
        self,
        updates: Any,
        *,
        time_index: Optional[int] = ...,
        scenario_id: Optional[str] = ...,
    ) -> UpdateReport: ...
    def _time_series_len(self) -> int: ...
    def _time_series_points(self) -> List[Tuple[str, Optional[float]]]: ...
    def _time_series_get(self, index: int) -> "_PioModule": ...
    def _scenario_entries(self) -> List[Tuple[str, Optional[float]]]: ...
    def _scenario_get(self, id: str) -> "_PioModule": ...
    def lowering_readiness_json(self, base_mva: float = ...) -> str: ...
    def lower_to_balanced(self, base_mva: float = ...) -> "_PioModule": ...
    def as_balanced_network(self) -> _BalancedNetwork: ...
    def as_multiconductor_network(self) -> _MulticonductorNetwork: ...
    def __repr__(self) -> str: ...
