"""Type stubs for the compiled ``caseio._caseio`` extension (PyO3).

Hand-written to match caseio-ext/src/lib.rs. Keep in sync when the Rust ABI
changes; this is what makes the ``py.typed`` package statically checkable.
"""

from typing import Optional

__version__: str

class CaseioError(Exception):
    """Raised by the caseio parser or converter for parse/data errors."""

class PyCase:
    @property
    def name(self) -> str: ...
    @property
    def base_mva(self) -> float: ...
    @property
    def source_format(self) -> str: ...
    @property
    def n(self) -> int: ...
    @property
    def n_branches(self) -> int: ...
    @property
    def n_gens(self) -> int: ...
    @property
    def n_loads(self) -> int: ...
    @property
    def n_shunts(self) -> int: ...
    @property
    def is_radial(self) -> bool: ...
    @property
    def n_connected_components(self) -> int: ...
    @property
    def buses(self) -> list[dict]: ...
    @property
    def loads(self) -> list[dict]: ...
    @property
    def shunts(self) -> list[dict]: ...
    @property
    def branches(self) -> list[dict]: ...
    @property
    def gens(self) -> list[dict]: ...
    def reference_bus_index(self) -> int: ...
    def connectivity_report(self) -> dict: ...
    def write(self) -> str: ...
    def __repr__(self) -> str: ...

def parse(path: str) -> PyCase: ...
def parse_string(content: str, name: Optional[str] = ...) -> PyCase: ...
def write(case: PyCase) -> str: ...
def convert(
    path: str, to: str, from_: Optional[str] = ..., /
) -> tuple[str, list[str]]: ...
